### ISSUE TITLE
Design an icon

### ISSUE THREAD

**Issue by rocka** [Rocket1184/electron-netease-cloud-music#1]
possible examples:

|electron(v1)|electron(v2)|electron-vue|
|:-:|:-:|:-:|
|<img src="https://raw.githubusercontent.com/electron/electron/79c00d8938abe5b983e372f6fc86128011f60b9c/default_app/icon.png" alt="electron" width="200px"/> |<img src="https://raw.githubusercontent.com/electron/electron/0f54e56389941bb2963adc46bd323924c208af3e/default_app/icon.png" alt="electron" width="200px"/>|<img src="https://raw.githubusercontent.com/SimulatedGREG/electron-vue/a87a56ee2acead6d6a4b76e815387f0322b7f9d6/template/build/icons/icon.png" alt="electron-vue" width="200px"/>|

**Comment by rocka** [comment]
<img src="https://github.com/Rocket1184/electron-netease-cloud-music/blob/7f36c627a1072735cfc557ff32bebd8790070536/assets/icons/icon.png?raw=true" alt="icon from 85ryan.com" width="200px"/>

**Comment by a-wing** [comment]
我一直想吐槽这个。。。。有点丑 ） 别打我。。。


> 在互联网的另一个角落（现在已经无法访问）发现的图标，原作者已经授权本项目使用 = =
> 
> icon from 85ryan.com

**Comment by rocka** [comment]
@a-wing 没有设计天赋，我也没办法呀 😶

**Comment by Fuermohao** [comment]
刘大爷加油，不过为什么 不能播放 具体的某首歌，还是说你只想 以歌单为单位来播放

**Comment by rocka** [comment]
> 为什么 不能播放 具体的某首歌，还是说你只想 以歌单为单位来播放

在搜索歌曲的页面点击歌曲条目后面的 ![添加到播放列表](https://user-images.githubusercontent.com/13914967/50721511-9c804b00-10fb-11e9-85e2-862a8d7a2ebe.png) 这个按钮就能把这首歌添加到播放列表里供下一首播放

因为我平时都是直接每日推荐和收藏的歌单点开就听，所以没专门去处理。不过搜索到的歌曲能添加到播放列表或者添加到歌单我觉得就够用了

还有如果有问题的话单独开一个 Issue 吧，不要在不相关的 Issue 里面回复 ...

**Comment by rocka** [comment]
抄了 KDE 的 [Breeze Icons](https://github.com/KDE/breeze-icons) 中的 [Telegram 图标](https://github.com/KDE/breeze-icons/blob/v5.60.0/icons/apps/48/telegram.svg)

<img src="https://gist.github.com/rocka/bff27b4644abce71e642e2e353104989/raw/bcfcd6cf00355028030fbec10cc6f9dc1ce11ea6/electron-ncm.svg?sanitize=true" width="200">

@a-wing 这个怎么样 = =

**Comment by a-wing** [comment]
感觉比原来那个强多了（

**Comment by rocka** [comment]
closed via 4e0d7b0

<img src="https://raw.githubusercontent.com/Rocket1184/electron-netease-cloud-music/a8712c0801f7999ce575705bd785cf1670313d1f/assets/icons/icon.svg?sanitize=true" width="200">

**Comment by Gabirel** [comment]
@rocka 这个图标在mac下面好模糊，模糊的不得了。原来的挺好看的啊，怎么就换了一个好模糊的。

截图看不出来，但是实际上在切换应用的时候可以很明显地看到图标高糊😥

**Comment by rocka** [comment]
@Gabirel 因为之前图标的作者就是为 macOS 设计的，本来就是 icns 格式的。现在的图标是 svg 格式的，但我没找到合适的生成 icns 格式图标工具，最大只能转出 128x128 的尺寸，图标太大的话可能看起来会糊掉。如果你有兴趣的话可以研究一下怎么生成高清的 icns 图标

**Comment by Gabirel** [comment]
@rocka 
1. 你给的所谓的高清的PNG是背景不透明的，我用了也没有用
2. 这个我就算是生成了icns的图标，每次我更新我不是只能再重新生成一次么？
3. 我也不是搞设计的，所以我也没有专业的办法，只能尝试去解决。如果实在是解决不了，不考虑换回去么？毕竟很模糊。如果真的解决不了，那我只能版本回退然后拒绝之后的所有升级了，直至解决。

**Comment by rocka** [comment]
@Gabirel 

点开看一下这个图片，确实是透明的啊 ... 要不直接打开链接看看？ https://user-images.githubusercontent.com/13914967/62129039-46c5f700-b308-11e9-93ad-9f1f95ac7d50.png

因为我搜到的很多转换图标到 icns 的方法都是 macOS only 的，我并没有 macOS 的设备，所以才做不了这个 ... 可以参考一下 Apple Community 中的[这个讨论](https://discussions.apple.com/thread/250169140)，或者试一下 [Image2icon](http://www.img2icnsapp.com/) 这个工具。

如果有效的话，把转换好的图标发上来，然后我 commit 到仓库里就好了。

**Comment by Gabirel** [comment]
@rocka 
你这个是512*512的大小么？有没有1024*1024的？还是已经是1024的了？

我试了一下效果还可以，肉眼上提升了好几个档次。但是我想问有没有更高清的了，如果有我就用更高清的再生成一次。

**Comment by Gabirel** [comment]
@rocka 
我看到的插件写着你的图片icon 1024x1024了，希望是对的。那文件如下：

[icon.icns.zip](https://github.com/Rocket1184/electron-netease-cloud-music/files/3447490/icon.icns.zip)

**Comment by yangdaweihit** [comment]
建议填加一下设置任务栏图标的功能。
