### ISSUE TITLE
enhance: Double click on the list item to play

### ISSUE THREAD

**Issue by Fuermohao** [Rocket1184/electron-netease-cloud-music#10]

**Comment by rocka** [comment]
这个功能有一些需要考虑的地方。在双击一首歌曲然后进行播放的时候，有两种选择：

1. 仅仅将这首歌加到播放列表然后播放
2. 把当前的播放列表替换成这首歌所在的列表，然后从这首开播放

选项 1 的话，点击 添加到播放列表 然后手动切换到下一曲就可以实现了。选项 2 其实是我很讨厌的一种方式，尤其实在搜索结果里面选择歌曲播放的时候，播放列表就会变得乱七八糟。所以才一直没做这个。

有什么好的建议吗？

**Comment by Fuermohao** [comment]
> 1. 仅仅将这首歌加到播放列表然后播放
我赞成选项1
> 选项 1 的话，点击 添加到播放列表 然后手动切换到下一曲就可以实现了。

添加到播放列表的当前播放项的上一条，然后播放该条。
比如当前播放列表 为`playlist`  正在播放`playlist`第5首歌 A，此时我双击了某个其余列表中的 歌B，然后我们把B添加到歌A的上一首，即插入到当前playlist的第五首，歌A之后的列表项顺移一位，当歌B播放完毕之后，`playlist`从歌A 继续往后播放。 这整个过程就像是在你的原有播放列表中间插了个队，并且立即播放。
我的建议就是这些，你觉的如何。

> 2.把当前的播放列表替换成这首歌所在的列表，然后从这首开播放
> 选项 2 其实是我很讨厌的一种方式

**Comment by rocka** [comment]
> 添加到播放列表的当前播放项的上一条，然后播放该条。

我觉得这样很不错，那就这么愉快的决定了

**Comment by Fuermohao** [comment]
Cheers!

**Comment by rocka** [comment]
现在实现逻辑是，在双击一首歌曲后：

1. 当前的播放列表中有相同的歌曲（id 相同），直接跳至该歌曲进行播放
2. 当前的播放列表中没有相同的歌曲。那么把这首歌加到播放列表的当前歌曲之前，然后从这首歌开始播放

**Comment by rocka** [comment]
等不及下一次发版本的话，可以先下载 CI 构建试一下 http://ncm.qn.rocka.cn/electron-netease-cloud-music_b1e3a4b.asar

不过最近在搞大重构，可能版本发得会比较快 233

**Comment by Fuermohao** [comment]
Good JOB! 不过我现在在装系统，被显卡驱动搞的很烦，装好系统再搞

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: rocka <notifications@github.com>
发送时间: Wednesday, January 9, 2019 11:37:29 PM
收件人: Rocket1184/electron-netease-cloud-music
抄送: How; Author
主题: Re: [Rocket1184/electron-netease-cloud-music] enhance: Double click on the list item to play (#10)


等不及下一次发版本的话，可以先下载 CI 构建试一下 http://ncm.qn.rocka.cn/electron-netease-cloud-music_b1e3a4b.asar

不过最近在搞大重构，可能版本发得会比较快 233

―

**Comment by Fuermohao** [comment]
嗯，滴水不漏，严谨

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: rocka <notifications@github.com>
发送时间: Wednesday, January 9, 2019 11:35:15 PM
收件人: Rocket1184/electron-netease-cloud-music
抄送: How; Author
主题: Re: [Rocket1184/electron-netease-cloud-music] enhance: Double click on the list item to play (#10)


现在实现逻辑是，在双击一首歌曲后：

  1.  当前的播放列表中有相同的歌曲（id 相同），直接跳至该歌曲进行播放
  2.  当前的播放列表中没有相同的歌曲。那么把这首歌加到播放列表的当前歌曲之前，然后从这首歌开始播放

―
