### ISSUE TITLE
非root用户点击时会遇到这个报错，root用户打不开软件

### ISSUE THREAD

**Issue by 1900011604** [Rocket1184/electron-netease-cloud-music#104]
1.非root用户点击时会遇到这个报错：
![2020-09-06 09-43-46 的屏幕截图](https://user-images.githubusercontent.com/65082432/92316399-f601f100-f025-11ea-8c63-20a59fff5af9.png)

点击确定后又可以打开软件。

2.root用户打不开软件。

**Comment by 1900011604** [comment]
![图片](https://user-images.githubusercontent.com/65082432/92316421-3a8d8c80-f026-11ea-9057-86f1c0a0d660.png)

重装软件解决不了

**Comment by rocka** [comment]
source map 还原出的位置是

```js
{
  source: 'webpack:///src/main/index.js',
  line: 95,
  column: 19,
  name: 'show'
}
```

https://github.com/Rocket1184/electron-netease-cloud-music/blob/a4e3fbd4597929bcee49694f2820344df3a4d7a3/src/main/index.js#L94-L97

所以这是，设置里开启了关闭窗口时最小化到托盘？是不是中途休眠过，然后托盘图标丢失了，再次点击图标打开，才出现这种状况？

看这个图标应该是 Manjaro GNOME 吧，应用版本， Electron 版本和 GNOME 版本分别是多少？

**Comment by 1900011604** [comment]
都是最新的，E-NCM是0.9, Electron是9，GNOME是3.36

**Comment by rocka** [comment]
这个情况是怎么出现的？安装之后，点击图标打开，就直接报错了吗？

看一下后台有没有 electron 和 electron-netease-cloud-music 进程正在运行，如果有的话都杀掉再试试？

另外 KDE 并不能复现这个问题，而我手头也没有 GNOME 环境 ...

**Comment by 1900011604** [comment]
我已经把GNOME删了并且装回KDE了

**Comment by 1900011604** [comment]
是的，安装之后点击图标即有这种情况。

我现在已经把GNOME删了……以后还是用KDE吧

**Comment by rocka** [comment]
下了一个 Manjaro GNOME 20.1-rc5 的 LiveCD ，没有复现。同样 Fedora 32 也没有复现。先 close 了。
