### ISSUE TITLE
树莓派4b 无法正常使用，打开就是白屏，求解决

### ISSUE THREAD

**Issue by nanjo712** [Rocket1184/electron-netease-cloud-music#105]
设备是树莓派4b 
无法正常使用，打开就是白屏，求解决
系统是manjaro ARM
从archlinuxcn上下载的

**Comment by rocka** [comment]
在终端里面运行一下，看看有没有输出？在白屏的时候，按下 <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> ，能不能呼出控制台，控制台中有没有报错？

**Comment by nanjo712** [comment]
终端运行：没有任何输出;
白屏按下ctrl+shift+i：没有任何效果

**Comment by nanjo712** [comment]
安装的electron版本为v10.1.1
electronNCM版本是0.9.24

**Comment by rocka** [comment]
这个问题是 electron@10 默认禁用了 remote 模块，但目前的 renderer 进程还有一部分功能在依赖它，初始化全局变量的时候找不到 remote 模块，就直接罢工了 ...

**Comment by nanjo712** [comment]
那么有什么办法启动这个模块吗？

**Comment by rocka** [comment]
40f1500e90f047cce4cd35ecfb60795336ada6e2 改回来了， [v0.9.25](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.25) 就能用了， archlinuxcn 应该也马上会更新版本。
