### ISSUE TITLE
windows 10如何安装？

### ISSUE THREAD

**Issue by northpoleforce** [Rocket1184/electron-netease-cloud-music#108]
按照readme下载**npm**（对应windows的话是指**Node.js**吧？安装后在cmd键入`node -v`后显示了版本，键入`npm -v`后也显示了版本）后在**cmd**键入`electron /path/to/electron-netease-cloud-music_*.asar`显示electron不是内部命令或外部命令，如何解决？

**Comment by rocka** [comment]
需要下载的是 electron ，而不是 nodejs 。

简单来说，可以先在 https://npm.taobao.org/mirrors/electron/ 下载对应版本的 electron ，比如 10.1.2 版： https://npm.taobao.org/mirrors/electron/10.1.2/electron-v10.1.2-win32-x64.zip

然后解压；把 release 中的 asar 文件重命名为 app.asar ，并复制到解压出的文件夹的 resource 子文件夹里面（这个文件夹中已经有了一个 default_app.asar）。然后双击解压出的文件夹中的 electron.exe ，即可运行。

如果用 npm 安装的话，装完 nodejs 后，再运行 npm install -g electron ，这样才能装上 electron 。如果你只是想运行一下这个程序，而不是开发的话，不建议这么做，因为 electron 在安装的时候会把安装文件缓存在用户目录里面，删起来还挺麻烦的。

**Comment by northpoleforce** [comment]
问题得到解决，非常感谢
