### ISSUE TITLE
希望可以增加跟随Gnome的主题的色彩来切换背景色（亮色/暗色）

### ISSUE THREAD

**Issue by a-kami** [Rocket1184/electron-netease-cloud-music#109]
RT，因为现在有一个插件可以在两个不同色调主题之间快捷切换
![image](https://user-images.githubusercontent.com/57009175/94446476-48749e80-01db-11eb-9383-add1231bb2fe.png)
像Telegram就可以跟随Gnome主题的色调自动切换暗色模式
![image](https://user-images.githubusercontent.com/57009175/94445198-c041c980-01d9-11eb-86b5-ef26d8174ebd.png)
还有大部分GTK应用也可以自动跟随Gnome的主题w

**Comment by Block81838** [comment]
this is electron, not gtk

**Comment by rocka** [comment]
https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.26 增加了根据系统主题切换背景色的功能，主进程用了 electron 的 nativeTheme ，渲染进程用了 CSS 的 prefers-color-scheme ，但具体支持程度就要取决于 electron 实现得怎么样了。不过至少在程序启动的时候，是能成功读取并跟随系统主题的，如果中途切换主题，不保证效果。
