### ISSUE TITLE
播放列表清空、删除某一首歌

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#11]
播放列表里面的歌曲如何更新（清空所有或者删除某一首）。

**Comment by rocka** [comment]
目前还没有这个功能 ... 可以点击歌单或者专辑详情界面的 <kbd>播放全部</kbd> 按钮来替换当前的播放列表

**Comment by roachsinai** [comment]
好的。

**Comment by rocka** [comment]
closed via f074aeb

![image](https://user-images.githubusercontent.com/13914967/52062005-a423fa00-25aa-11e9-8a8e-f83e3566f07f.png)

安装 [v0.7.8](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.7.8) 就能用上了

**Comment by roachsinai** [comment]
厉害了！
