### ISSUE TITLE
播放一段时间后点下载后会卡住

### ISSUE THREAD

**Issue by northpoleforce** [Rocket1184/electron-netease-cloud-music#110]
如下图
![image](https://user-images.githubusercontent.com/59782385/95204089-2fd93980-0816-11eb-9aa0-f3def509f685.png)
另，啥时有下载整个歌单歌曲的功能（~~小声不是~~

**Comment by rocka** [comment]
就一张图，也看不出来是哪里卡住了啊 😅

具体是哪些操作导致卡住的？点的是歌词左边那个下载，还是下面播放栏里的下载？如果是下面播放栏里的下载，是在哪个界面点击的？卡住之后的现象是什么？整个界面都不动了，还是只是部分控件没有响应？重复导致卡住的操作，能稳定重现卡住的现象吗？

**Comment by northpoleforce** [comment]
# 不能稳定重现卡住现象（*疑似是小概率事件*
bug详情：歌曲进度条不动（**且界面显示在播放，实际并没有，点击暂停键不会响应**），界面可操作
