### ISSUE TITLE
[Feature Request] 下载目录设置

### ISSUE THREAD

**Issue by su226** [Rocket1184/electron-netease-cloud-music#112]
我的电脑的音乐目录是~/音乐，但是软件默认下载到~/Music/ElectronNCM，希望增加下载目录的设置，或者自动检测音乐目录。
系统：Manjaro (Linux 5.8.18)
Electron：10.1.5
软件：0.9.26

**Comment by thaoeu** [comment]
有类似的需求，同时希望可以匹配本地音乐，有些文件命名和软件格式不同。
