### ISSUE TITLE
希望能在正在播放的曲子那里添加标签

### ISSUE THREAD

**Issue by Firestar-Reimu** [Rocket1184/electron-netease-cloud-music#113]
![Screenshot_20201228_154650](https://user-images.githubusercontent.com/65082432/103198786-2ac2ec80-4924-11eb-8193-f728b9f419d3.png)

比如说，正在播放的曲子是61号，但是歌单里看不出任何区别，没有原来那个喇叭标记，很难找出听的是哪一首曲子

**Comment by rocka** [comment]
b67d530

![image](https://user-images.githubusercontent.com/13914967/140644684-5cfd9c0b-9482-4a2e-97ef-4cec11cc585b.png)
