### ISSUE TITLE
你好，我的程序会不定期出现无法登录的情况。

### ISSUE THREAD

**Issue by thaoeu** [Rocket1184/electron-netease-cloud-music#114]
request to https://music.163.com/weapi/login/cellphone failed, reason: net::ERR_CERT_AUTHORITY_INVALID

与此同时网页登录页面也一片空白。

本地已下载及缓存的音乐可以正常播放。

**Comment by thaoeu** [comment]
系统：5.10.15-1-MANJARO
软件：0.9.26-1

**Comment by thaoeu** [comment]
electron ：v11.2.3
我看了#111，也试了网页版网易云登录、播放都没有问题。

这种情况先前出现过，我尝试过重新安装、清空我能找到的目录等方法皆无效。

过了一段时间再次打开就突然正常了，直到今天下午再次这样。

**Comment by thaoeu** [comment]
有尝试了#91的方法，关闭代理，切换到另一条宽带都没效果。
同时前些天正常的时候一直开着GFW模式，无法确定是否和代理有关。

**Comment by rocka** [comment]
ERR_CERT_AUTHORITY_INVALID 证书颁发机构无效，可能是 DNS 被污染了，解析到了错误的 IP 地址？下次如果再出现这种情况，打开浏览器试试网页版云音乐能不能正常加载。

另外顺便运行一下

```
drill music.163.com
```

看看解析出来的地址

**Comment by thaoeu** [comment]
感谢大佬！

确实解析出了个奇怪的地址。

换了台电脑访问网易云网页版提示 Someone could be trying to impersonate the site and you should not continue.
