### ISSUE TITLE
Electron 6.1.12 依赖是必须的吗？

### ISSUE THREAD

**Issue by 1900011604** [Rocket1184/electron-netease-cloud-music#115]
发现您的打包里面有两个Electron，是否可以考虑只用高版本的那一个，为什么需要两个Electron呢？

**Comment by rocka** [comment]
是指哪里的包？什么地方有两个 Electron ？

**Comment by 1900011604** [comment]
Archlinux CN的包

https://repo.archlinuxcn.org/x86_64/

**Comment by rocka** [comment]
是说这个包吗 https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/electron-netease-cloud-music/PKGBUILD ？

但这里只依赖了系统 Electron ，也没有指定版本

**Comment by 1900011604** [comment]
好的谢谢

**Comment by rocka** [comment]
所以为什么会有两个 Electron 啊，还是那么旧的版本 ... 是在自己构建吗？

**Comment by 1900011604** [comment]
**非常抱歉**

我又查了一下，electron6不是来源于网易云音乐，而是geogebra

**Comment by 1900011604** [comment]
非常抱歉

我又查了一下，electron6不是来源于网易云音乐，而是geogebra
