### ISSUE TITLE
旋转黑胶唱片渲染模糊

### ISSUE THREAD

**Issue by swwind** [Rocket1184/electron-netease-cloud-music#117]
Electron: 12.0.4
Chrome: 89.0.4389.114
Node: 14.16.0
V8: 8.9.255.24-electron.0

Video: https://user-images.githubusercontent.com/26316494/115502164-0e6a0780-a2a7-11eb-9df2-4c7029380495.mp4

OS: Arch Linux
Kernel: x86_64 Linux 5.11.15-arch1-2
Resolution: 1920x1080
WM: Awesome

似乎在 Windows 下也有类似情况。

**Comment by rocka** [comment]
我也遇到了，似乎只要在播放状态下打开唱片/歌词那个页面就会触发，暂停一下就恢复了。而在暂停状态下打开则不会出现。

**Comment by xyzhou-1** [comment]
我也遇到了，似乎是因为 archlinux 将 electron 滚到了 12？使用 electron11 好像就解决了。对前端不了解，也不知道是不是这个原因。

**Comment by Lapis-Apple** [comment]
Same problem.
Arch Linux, too.

**Comment by rocka** [comment]
试了一下升级到 Electron 13 之后这个问题消失了，要不先忍忍吧 ...

**Comment by rocka** [comment]
今天 Arch 更新 electron 13.1.2 了，问题~~消失~~解决了， Issue 就先关了吧 ...
