### ISSUE TITLE
托盘图标显示错误

### ISSUE THREAD

**Issue by Stitch-Zhang** [Rocket1184/electron-netease-cloud-music#119]
托盘图标变成electron图标，清除所有应用数据和重新安装后也无效
![tray_icon](https://user-images.githubusercontent.com/61350804/117455719-0930dc00-af7a-11eb-9b1f-8ff8a3926f7d.gif)

Electron: 12.0.6
Chrome: 89.0.4389.128
Node: 14.16.0
V8: 8.9.255.25-electron.0
System:Manjaro

**Comment by rocka** [comment]
是 KDE 桌面吗？用的什么图标主题？安装 libappindicator-gtk3 再试试呢？

**Comment by Stitch-Zhang** [comment]
6666666解决了，确实是图标的问题。用的是KDE桌面，图标是` Tela ` ，改成默认的图标就可以了👍

**Comment by rocka** [comment]
原来 KDE 也会有这种问题啊，我原本以为只有 Unity 会这样，还专门加了一个 hack 。试试

```
env XDG_CURRENT_DESKTOP=Unity electron-netease-cloud-music
```

这样运行，在使用非默认图标主题的情况下也能正常显示托盘图标。

electron 请求的图标名字是 `electron-netease-cloud-music1_1` 这种，然后提供了一个同名的 png 文件做图标，在默认主题下是没什么问题的。但有些图标主题提供了名为 `electron` 的图标，找图标的时候每次去掉一段 `-` 开头的后缀，就给匹配上了。

**Comment by Stitch-Zhang** [comment]
这种方法可用，建议下次更新加入`archlinuxcn`源中🥳

**Comment by rocka** [comment]
electron 这个托盘图标实现着实不太行，而且我自己平时也不用托盘 😅 KDE 自带的那个媒体控制就很好用，而且还比托盘好看 ...
