### ISSUE TITLE
[bug] 喜欢的音乐不显示 / 歌单只显示一首歌

### ISSUE THREAD

**Issue by Lapis-Apple** [Rocket1184/electron-netease-cloud-music#121]
打开“我喜欢的音乐”：
![图片](https://user-images.githubusercontent.com/62464927/121794082-0344af80-cc38-11eb-8d8d-3994cc7bab59.png)
打开任意公开歌单：
![图片](https://user-images.githubusercontent.com/62464927/121794089-1a839d00-cc38-11eb-82c3-712cd1afff3e.png)
（只显示第一首歌）

Electron 11, Arch Linux. Package from ArchLinuxCN.

**Comment by rocka** [comment]
进入应用设置，打开开发者工具，在控制台中执行这些

```js
(function(){
    window.onbeforeunload = null
    localStorage.cookiebak = localStorage.cookie
    ck = JSON.parse(localStorage.cookie)
    delete ck.WM_NI
    delete ck.WM_NIKE
    delete ck.WM_TID
    ck.appver='4.3.1'
    ck.buildver='1513567509'
    ck.channel='google'
    ck.mobilename='linux'
    ck.os='pc'
    ck.osver='10.0.0'
    localStorage.cookie = JSON.stringify(ck)
})()
```

然后按下 <kbd>Ctrl</kbd> + <kbd>R</kbd> 重载页面，应该就可以了

估计是网易又增加了一些对 cookie 的检查，不过检查的都是一些无关紧要的字段 ...

**Comment by rocka** [comment]
这个 Issue 先别关闭，估计很多用户都会遇到，还是发个版吧 ...

**Comment by Lapis-Apple** [comment]
感谢，执行那些有效。
建议发个版。
顺带也建议看看 Electron 12 的那个适配 bug（唱片模糊那个）

**Comment by rocka** [comment]
> 顺带也建议看看 Electron 12 的那个适配 bug（唱片模糊那个）

那个我真没什么头绪，如果是浏览器渲染问题这边好像也没法修 ...

**Comment by Lapis-Apple** [comment]
> > 顺带也建议看看 Electron 12 的那个适配 bug（唱片模糊那个）
> 
> 那个我真没什么头绪，如果是浏览器渲染问题这边好像也没法修 ...

（（（
那改下包的依赖（electron11包）和那个启动用的sh脚本的启动命令吧（

**Comment by rocka** [comment]
closed via 7cb33c8
