### ISSUE TITLE
[feature request] Wayland support

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#122]
我使用的 Gnome + Wayland + fractional scaling，electron-netease-cloud-music 会默认使用 Xwayland 启动，但是会变得模糊。Electron 12 加入了 native Wayland 支持，只需要加两个启动选项就能启用，可以解决模糊的问题。也就是需要这样启动

```
electron /usr/lib/electron-netease-cloud-music --enable-features=UseOzonePlatform --ozone-platform=wayland
```

希望能够增加一个内置的选项，这样就不用去覆盖 /usr/bin/electron-netease-cloud-music 或者 .desktop 文件。

**Comment by 1900011604** [comment]
Firefox也会模糊来着……我这边是KDE，我现在都不用Wayland

**Comment by rocka** [comment]
尝试了一下使用 Electron 的 [commandLine API](https://www.electronjs.org/docs/latest/api/command-line)

```js
app.commandLine.appendSwitch('enable-features', 'UseOzonePlatform');
app.commandLine.appendSwitch('ozone-platform', 'wayland');
```

在应用启动后添加 command line switch ，能成功启动，但无法渲染界面，就像这样

![image](https://user-images.githubusercontent.com/13914967/140610033-49725d2f-230d-4c01-9e85-dc9a205118c3.png)
这时候如果把鼠标放到正确的位置，是可以响应点击事件的，也能用 MPRIS 控制播放音乐。

---

又做了几次试验，发现 `--enable-features=UseOzonePlatform` 似乎只有放在命令行参数里面才有效；而 `--ozone-platform=wayland` 用 Electron 的 appendSwitch 来添加也能生效，不知道是不是 Electron 的 bug 。

**Comment by icepie** [comment]
```bash
#!/bin/bash
exec electron /usr/lib/electron-netease-cloud-music "$@"
```

可以加个 `"$@"`

再

```bash
$ electron-netease-cloud-music --enable-features=UseOzonePlatform --ozone-platform=wayland
```

就可 `wayland` 模式运行了

然后如果你用的是 `gnome` 会发现缺失了系统窗口, 可以通过 `WaylandWindowDecorations` 打开

```bash
$ electron-netease-cloud-music --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```

**Comment by DreamMaoMao** [comment]
[Desktop Entry]
Name=netease
Exec=electron-netease-cloud-music --force-device-scale-factor=1 %U 
Terminal=false
Type=Application
Icon=netease-cloud-music
StartupWMClass=netease
Categories=Network;
Comment=netease
Keywords=netease;

把缩放还原回 --force-device-scale-factor=1  就不会模糊  ,因为默认是x11模式不支持wayland的分数缩放

如果要缩放使用xwayland 应用的话,最优解是直接修dpi,这样既能缩放x11应用 又不会模糊

 echo "Xft.dpi: 140" | xrdb -merge

**Comment by rocka** [comment]
现在（其实早就） Arch 打包的 electron 会读取 ~/.config/electron-flags.conf 文件了，所以只需要

```
--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
--enable-wayland-ime
```

就可以了
