### ISSUE TITLE
专辑封面分辨率显示不正常

### ISSUE THREAD

**Issue by Keanu-42** [Rocket1184/electron-netease-cloud-music#125]
- 问题描述：在听歌时，点击左下角打开歌曲界面，大概率会遇到封面模糊的情况。

- 解决办法：点击暂停，或使窗口全屏化再缩小回来。

- 附件：

![before](https://cdn.jsdelivr.net/gh/Keanu-42/Keanu-42.github.io@v1.1.2/Gnome使用细节/before.png)

**Comment by Keanu-42** [comment]
- 还有一个问题：请问后面会加入 **音乐切换时渐入渐出** 这个功能吗？

**Comment by rocka** [comment]
duplicate #117 ：请更新 electron 版本到 13 以上

关于音乐淡入淡出功能，没有特别的计划，如果哪天想起来了可能会做
