### ISSUE TITLE
[Feature Request] 播放器内置音量调节

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#13]
希望有个内置音量的调节。

这样，不同的程序之间声音就可以重叠而不需要调节全局音量。

**Comment by rocka** [comment]
这个我一般都用桌面环境自带的音量调节 ... 不过加一个也不是不行

![image](https://user-images.githubusercontent.com/13914967/52177064-cca03400-27f6-11e9-97c2-90e426fd7fe2.png)

**Comment by roachsinai** [comment]
@rocka 这个还是加一个好2333

**Comment by rocka** [comment]
我在考虑加在什么地方 ... 有一个想法是把 音量调节 放在现在的 播放列表循环模式 按钮的地方，然后把 播放列表循环模式 移动到播放列表里面 `共 xx 首` 的位置

**Comment by roachsinai** [comment]
放在歌曲播放进度条前面咋样？感觉循环模式不直接显示好像不好。

**Comment by roachsinai** [comment]
然后哪个音量大小那个调节的浮在下面？

**Comment by rocka** [comment]
emmm 怎么放在前面 ... 有点没懂

**Comment by roachsinai** [comment]
![screenshot_20190216_223201](https://user-images.githubusercontent.com/9500049/52901180-b3f23e00-323a-11e9-9713-b48f85cedc41.png)

**Comment by roachsinai** [comment]
或者把收藏和添加到歌单挪到评论的旁边，把音量放过去。
![screenshot_20190216_223545](https://user-images.githubusercontent.com/9500049/52901212-38dd5780-323b-11e9-81fa-21669834ade7.png)

**Comment by rocka** [comment]
@Gabirel @roachsinai 

添加了音量控制，并把 收藏 移动到了播放界面的 评论 左边

![image](https://user-images.githubusercontent.com/13914967/53328576-41ade780-3925-11e9-8d1e-4ab1840e63ca.png)

- 单击音量图标可以显示/隐藏 popup

- 鼠标放在音量图标或者 popup 上时滚动滚轮可以调节音量大小。这时 popup 会显示，并在输入停止 750ms 后自动隐藏

- 鼠标中键点击音量图标可以快速静音/取消静音

总之就是完全抄袭 KDE System Tray 音量图标的交互。可以下载 [CI 构建](https://ncm-releases.herokuapp.com/) 先测试一下。

**Comment by rocka** [comment]
closed via [v0.8.3](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.3)
