### ISSUE TITLE
滑动会导致程序卡死

### ISSUE THREAD

**Issue by 13896089747** [Rocket1184/electron-netease-cloud-music#132]
在任意可以滑动的界面滑动都会导致卡死
![1](https://user-images.githubusercontent.com/38597492/151301829-2c181a0c-48ce-476a-a271-703a50533bc0.gif)
electron16 from archlinuxcn

**Comment by rocka** [comment]
`community/electron 16.0.7-2` 确实可以复现，安装一个别的依赖 electron 的应用（比如 [geogebra](https://archlinux.org/packages/community/x86_64/geogebra/)），找个有滚动条的地方滑一下也会直接崩溃。但是用 npm install 下来的 electron 16.0.7 运行没有问题，所以应该是 Arch 的 electron 打包有问题 ...

**Comment by 13896089747** [comment]
降级后确实没这个问题了，不知道下一版还会不会有这个问题

**Comment by rocka** [comment]
已经有 bug report 了
https://bugs.archlinux.org/task/73518?project=5&string=electron
