### ISSUE TITLE
打开白屏

### ISSUE THREAD

**Issue by bigshans** [Rocket1184/electron-netease-cloud-music#135]
在 Arch 上使用，现在打开白屏。

![图片](https://user-images.githubusercontent.com/26884666/162352963-7b1c7f0c-e5c1-4e48-bfc1-9ee8a64e557b.png)

删了 .config 下的缓存似乎不起作用，虽然我最近重置了密码，但删了缓存应该能有效果。

然后改用低版本的 electron 生效，目前 electron 是 18 ，我用 electron 17 能够解决。

如果不能按照最新版 electron 兼容，还请用具体版本的 electron 。

**Comment by rocka** [comment]
目前 Arch 仓库里 electron 18.0.1-1 打包有问题，运行试会出现 Assertion fail

https://bugs.archlinux.org/task/74328

npm 上安装的 electron 则没有问题

**Comment by rocka** [comment]
https://github.com/archlinuxcn/repo/issues/2721
