### ISSUE TITLE
播放音乐没有声音

### ISSUE THREAD

**Issue by potuo** [Rocket1184/electron-netease-cloud-music#138]
播放音乐没有声音

`OS: Arch Linux x86_64`
`Host: TUF Gaming FX505GT_FX95GT 1.0`
`Kernel: 5.18.1-zen1-1-zen`
`Uptime: 13 mins`
`Packages: 1229 (pacman)`
`Shell: zsh 5.9`
`Resolution: 1920x1080`
`WM: i3`
`Theme: Breeze [GTK2/3]`
`Icons: breeze [GTK2/3]`
`Terminal: alacritty`
`CPU: Intel i5-9300H (8) @ 4.100GHz`
`GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q`
`GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]`

**Comment by potuo** [comment]
> 试试用 Chromium 或 Chrome 播放个音频有声音吗？我这里正常。

使用Chrome可以播放声音,Chromium不行

**Comment by haotian2004** [comment]
我这里都不行

**Comment by rocka** [comment]
有没有可能和这个是同样的问题 https://github.com/Rocket1184/electron-netease-cloud-music/issues/140#issuecomment-1169469875

**Comment by haotian2004** [comment]
我搞了个PR，麻烦看一下
