### ISSUE TITLE
[Feature Request] Tray icon Requested

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#14]
有了后台后，就不用把程序放在前台了，可以节省很多空间。

**Comment by rocka** [comment]
其实我个人不是很喜欢 Tray Icon 的 ... 大部分桌面环境都实现了 [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/)，可以通过自带的 Applet 来控制媒体播放，所以一开始就没有考虑实现自己的 Tray Icon。

不过可以考虑把关闭窗口时的行为从退出程序改为隐藏主窗口，这样也不会占用“任务栏”的空间，同时也可以通过 MPRIS 的 `Raise` 方法来重新打开主窗口。

有什么好的建议吗？

**Comment by Gabirel** [comment]
XFCE4的那个Applet并不好用，播放还是需要开一个前台，很麻烦，而且还需要占一个任务栏位置。
所以Tray icon的方式就是你所说的隐藏主窗口不占用任务栏的方式啊，难道不是么

**Comment by rocka** [comment]
[`v0.8.0`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.0) 重写了 MPRIS 实现，经过我在 Xfce 虚拟机里面的测试感觉应该能达到“好用”的水准了 ... 请务必帮忙测试一下。

至于 Tray Icon 会有一个选项的。在做了，真的在做了 ...

**Comment by Gabirel** [comment]
测试没问题啊，我也是要一直要用。Deepin的网易云自从王勇不干了以后就跟坨屎一样，打开都打开不了。

但是问题是你那个asar的怎么用啊？我在`/usr/lib/electron-netease-cloud-music`下面没有这个东西可以替换的，arch源里也没有收到更新（顺便吐槽一下为什么安装路径是在`/usr/lib/`下的，一般都是在`/usr/share/`下的）

**Comment by rocka** [comment]
安装路径在 `/usr/lib/electron-netease-cloud-music`

可以安装 Arch 源里的 `asar` 这个包，然后

```console
asar e app.asar app/
```

把 asar 文件解开，然后把文件覆盖一下，反正下次升级的时候就又覆盖回来了。

顺便说一句 `pacman -Ql pkgname` 可以列出某个包安装了哪些文件

**Comment by Gabirel** [comment]
![image](https://user-images.githubusercontent.com/12933851/52786704-89678000-3096-11e9-99a3-6ad5fae57191.png)
`0.8.0`了更新了啥？我桌面环境上什么变化都看不到，感觉和之前的版本没有一丢丢丢的区别:sad:

**Comment by rocka** [comment]
把 MPRIS 模块完全重写了，不再依赖 native module。UI 上确实没什么变化。之前我在虚拟机里测试的时候，启动程序，然后立即打开 PulseAudio Applet 会导致整个桌面卡住十几秒，现在不会了。

另外桌面环境的媒体控制 Applet 真的不好用吗，我觉得没有这么不堪吧？播放控制有开始/暂停，上一首下一首，再加上能显示正在播放的曲目名称以及歌手似乎就已经够了 ... 还有什么不能满足的需求吗？

**Comment by Gabirel** [comment]
酱紫啊，那这个的确是很快了。之前确实很慢，我还以为是electronic-app的问题。

Applet不好用，太鸡肋了。因为平时基本没有有点击音量图标，然后去切换歌曲。
我的听歌模式：打开NCM->打开私人FM->把NCM移动到workspace 2
如果有不爱听的，我会点“删除”（网易云的表示不喜欢，后续歌曲不会继续推荐类似的歌曲），然后切换回工作workspace

所以没有使用applet的情景。所以相比之下，在这个状态下Tray icon的方式可以不用切换workspace，速度更快一点。

PS：据我所知道的，包括我的身边人，听网易云基本上听的私人FM和别人的歌单模式是最多的

**Comment by rocka** [comment]
@Gabirel 有这些选项的话应该够用了吧，还缺什么吗

![image](https://user-images.githubusercontent.com/13914967/52847009-0b62b200-3146-11e9-99dd-9476c88723eb.png)

**Comment by Gabirel** [comment]
大佬的效率真的是高诶！

不知道这个tray icon有没有黑白模式以适用于不同的主题呢？比如我的是白色的话，假如这个tray icon是白色或者透明的话，可能效果就会不是特别好。

请问，这个双击tray icon可以直接显示主界面吗？至于其他功能，我觉得很完善了。甚至都没有想到还可以加喜欢和不感兴趣。赞

**Comment by rocka** [comment]
可以有一个选项设置 Tray Icon 的颜色，这个一开始就在计划中的。双击 Tray Icon 显示界面可能不行，改成单击可以吗？

**Comment by Gabirel** [comment]
那可以啊，能单击就没必要双击嘛，我还以为是无法实现单击什么的。那我觉得就已经很完善了

**Comment by rocka** [comment]
@Gabirel 应该做好了，请下载最新 CI 构建测试 https://ncm-releases.herokuapp.com/

添加了三个设置：

- 显示托盘图标
- 托盘图标颜色（黑/白）
- 关闭窗口时（退出程序/隐藏到托盘）

至于单击托盘图标显示界面的问题，不保证可用。 Electron 有两种托盘图标实现， `GtkStatusIcon` 和 `appindicator`，前者在高分屏上会模糊，后者不能响应单击事件。如果系统中有 `libappindicator`，会优先使用后者。

**Comment by Gabirel** [comment]
请问这个特性已经存在于`0.8.0-3`中了吗？

**Comment by rocka** [comment]
没有，还没发布新版本，请先下载 CI 构建测试 …
