### ISSUE TITLE
archlinux 无法播放音乐，以下是网络相关

### ISSUE THREAD

**Issue by haotian2004** [Rocket1184/electron-netease-cloud-music#140]
```console
wuming:~ $ ifconfig 
enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.66.133  netmask 255.255.255.0  broadcast 192.168.66.255
        inet6 fe80::2a9c:2904:*****  prefixlen 64  scopeid 0x20<link>
        inet6 2408:821a:1a11:・*******  prefixlen 64  scopeid 0x0<global>
        inet6 2408:821a:1a11:e***** prefixlen 128  scopeid 0x0<global>
        ether 00:25:ab:4a:a3:be  txqueuelen 1000  (Ethernet)
        RX packets 249982  bytes 358975480 (342.3 MiB)
        RX errors 0  dropped 32  overruns 0  frame 0
        TX packets 82426  bytes 8193540 (7.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by rocka** [comment]
浏览器（ Chrome/Chromium 或 Firefox ）打开网页版网易云音乐 https://music.163.com 能播放吗？

**Comment by haotian2004** [comment]
不能

**Comment by rocka** [comment]
> 不能

那显然和 Electron 没有关系 ... 你应该首先解决一下浏览器不能放的问题

**Comment by rocka** [comment]
是不是因为这个

https://archlinux.org/news/undone-replacement-of-pipewire-media-session-with-wireplumber/

中文翻译：

https://www.archlinuxcn.org/undone-replacement-of-pipewire-media-session-with-wireplumber/

**Comment by haotian2004** [comment]
sudo pacman -Syu pipewire-media-session
[ WARN:0@2.781] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@2.787] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@2.787] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Face detection timeout reached
[sudo] wuming 的密码：
:: 正在同步软件包数据库...
 core 已经是最新版本
 extra 已经是最新版本
 community 已经是最新版本
 multilib-testing 已经是最新版本
 multilib 已经是最新版本
 archlinuxcn 已经是最新版本
:: 正在进行全面系统更新...
正在解析依赖关系...
正在查找软件包冲突...
:: pipewire-media-session 与 wireplumber 有冲突。删除 wireplumber 吗？ [y/N]

**Comment by haotian2004** [comment]
这个写到安装冲突软件包里面把
确实是这个问题

**Comment by haotian2004** [comment]
没事了，close
