### ISSUE TITLE
歌曲/歌单发布评论失败

### ISSUE THREAD

**Issue by SamLukeYes** [Rocket1184/electron-netease-cloud-music#143]
[录屏 2022年08月11日 00时54分44秒.webm](https://user-images.githubusercontent.com/12882091/183970694-2758163e-4fd7-4a53-b29a-c8e4f349a9d6.webm)

退出后重新登录仍是如此。当前版本为 0.9.35。

**Comment by rocka** [comment]
别的功能可以正常使用吗？比如收藏歌单，私人 FM 之类的。我这里目前不能复现，可能是网易改了 cookie 格式之类的。

可以试一下先登出，然后打开侧栏 应用设置 -> 启动开发者工具，在 Console 里运行

```js
window.onbeforeunload = null
["cookie", "user"].forEach(i => localStorage.removeItem(i))
```

然后登出，完全退出程序，再打开重新登录

**Comment by SamLukeYes** [comment]
![图片](https://user-images.githubusercontent.com/12882091/184053202-6124bf61-a6f1-4d6d-bbac-112960235f27.png)

登出后进行上述操作，并清除了浏览器缓存，重新启动程序后更换了登录方式（尝试了应用内登录和网页端账号密码登录），问题依然存在。收藏歌单和私人 FM 都可以使用。

**Comment by rocka** [comment]
测了半天，歌单/MV/视频可以评论，但歌曲/专辑没法评论。不知道网易又暗改了什么。

**Comment by rocka** [comment]
![image](https://user-images.githubusercontent.com/13914967/184277416-cb1f04f7-d0d4-40f8-a2c7-c31edc66547c.png)

这个提示看起来像是被风控了

**Comment by rocka** [comment]
尝试了一下把 Cookie 里的设备信息伪装成 Android 就可以了，参考了 https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1442 和 https://github.com/chen310/NeteaseCloudMusicApi/commit/2bd00f932fd049753f18ce203a0160a42c63298f

**Comment by rocka** [comment]
should be fixed in https://github.com/Rocket1184/electron-netease-cloud-music/commit/6ee71031bb2f6e495cdbd27c5fb389f830a492a0
