### ISSUE TITLE
[Feature Request] 希望可以在 我的收藏 - 专辑页面 添加一个搜索功能

### ISSUE THREAD

**Issue by ImVeri** [Rocket1184/electron-netease-cloud-music#145]
每次想听喜欢的专辑都要一个一个的翻好久，呜呜呜…

**Comment by rocka** [comment]
000fe62 加了搜索收藏，除了主播电台，别的都能搜

![image](https://github.com/Rocket1184/electron-netease-cloud-music/assets/13914967/f27d48bc-125e-4430-87a5-34cbc6a1055b)

![image](https://github.com/Rocket1184/electron-netease-cloud-music/assets/13914967/d8bcf356-d89c-422d-a8cc-61e9526358d0)

**Comment by ImVeri** [comment]
好诶！爱你！咕
