### ISSUE TITLE
[Bug] 日推页面左侧统计数据失效

### ISSUE THREAD

**Issue by zetako** [Rocket1184/electron-netease-cloud-music#146]
如图，左侧统计数据失效了；没有在其他环境测试过，不知道是不是我的环境的问题。
软件包：archlinuxcn打包的0.9.36-1版本
系统：Manjaro + KDE
![image](https://user-images.githubusercontent.com/54136740/187579898-2ff09c1d-1a32-4a17-b461-a2c741016658.png)

**Comment by rocka** [comment]
是 6ee71031bb2f6e495cdbd27c5fb389f830a492a0 的问题，这个统计是直接抓取的桌面网页版数据，因为换成了 Android 的 UserAgent ，不给返回桌面版网页了。另外歌单和专辑页面左侧的“相关推荐”也显示不出来了。

**Comment by rocka** [comment]
should be fixed by 34a553c
