### ISSUE TITLE
“网页登录”有时无法正确判定登录状态

### ISSUE THREAD

**Issue by haotian2004** [Rocket1184/electron-netease-cloud-music#148]
我重装了一下arch,网易云账号登陆会掉，提示重新登陆，但是它那个浏览器是登陆着账号的

**Comment by haotian2004** [comment]
就现在还是无法正常的   
登陆保持

**Comment by rocka** [comment]
我这边登录倒是还没出现什么问题 … 但确实已经很久没有重新登录过了，这几天抽空看看吧

**Comment by Lapis-Apple** [comment]
同。

**Comment by Lapis-Apple** [comment]
我这里的具体表现为：

应用内登陆无法使用：“网络太拥挤，请稍后重试！”

浏览器登陆可以使用，可以登录，但是关闭并重新打开 App 之后，大概率会没有办法再自动登陆。再次点击浏览器登陆会发现那里面的网易云网页版是登陆着的，但是直接点击 App 的确认登陆成功按钮会报“根本没有登陆成功”。只有在网页版网易云注销重新登陆才可以。

但是这似乎是概率性事件..

**Comment by Reisen1969** [comment]
一样的问题

**Comment by rocka** [comment]
我换了几台设备和账号测试了一下，又不能复现这个问题了

**Comment by rocka** [comment]
似乎只有在网页中使用“扫码登录”的时候有问题？我这边测试使用邮箱和手机号登录都正常，只有“扫码登录”有几率出问题 ...

**Comment by yjun123** [comment]
发行版为Arch Linux， 软件版本为 0.9.37-1，electron 版本为 25
出现的问题为无法登录，详细描述如下：

点击登录 -> 应用内登录 -> (手机号/密码均确认正确)提示 登陆失败,请进行安全验证

**Comment by yjun123** [comment]
> 发行版为Arch Linux， 软件版本为 0.9.37-1，electron 版本为 25 出现的问题为无法登录，详细描述如下：
> 
> 点击登录 -> 应用内登录 -> (手机号/密码均确认正确)提示 登陆失败,请进行安全验证

网页端手机号登录，做个人机验证后，登录成功了! ‘'>".

**Comment by rocka** [comment]
@yjun123 

> 提示 登陆失败,请进行安全验证

根据 https://github.com/Binaryify/NeteaseCloudMusicApi/commit/4fc46a046c146aea178b42da0e2fe63d9619c637 提到的，手机和邮箱登录都已经被网易限制，而且不能绕过。只能先用网页登录。

**Comment by Puqns67** [comment]
网页端正常登录，点完成提示没有登录成功，用账号密码登录能登录成功，但是重启软件后就提示登录失败。

ArchLinux 所有包都保持最新
Electron 25.3.1
ElectronNCM 0.9.38
包来源为 archlinuxcn

**Comment by LAST7** [comment]
网页端无法使用二维码登录，手机短信登录后有错误提示，关闭登录窗口后软件可以正常登录，重启后提示登录失败。

Achrchlinux
Electron 25.3.2
ElectronNCM 0.9.38-1 (archlinuxcn)
