### ISSUE TITLE
播放一个歌手的音乐，查看歌手之后无法返回

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#15]
1. 播放一首歌，在显示歌词界面点击歌手。
2. 进入歌手界面之后，在随机选择一首歌曲播放。
3. 重复步骤1，这时候点击左侧的返回，卡住不动。

**Comment by rocka** [comment]
补充条件：只有当步骤 1 与 3 选择的歌手相同时才会出现

**Comment by rocka** [comment]
vue-router 的 abstract mode 导致了这个问题，出现两个相同路由的时候，back 会失效。已经提了 [Issue](https://github.com/vuejs/vue-router/issues/2607)，如果他们认为不是 bug 的话那可能需要换一种方式实现了。

**Comment by rocka** [comment]
vue-router 那边根本没人管 ... 那我还是存 `sessionStorage` 算了

**Comment by rocka** [comment]
closed via https://github.com/Rocket1184/electron-netease-cloud-music/commit/5c4840c8f91f024c3fe790c090989ec47480ec83
