### ISSUE TITLE
Bug: local music server not work properly

### ISSUE THREAD

**Issue by ClSlaid** [Rocket1184/electron-netease-cloud-music#150]
![图片](https://user-images.githubusercontent.com/44747719/207800232-bb6298f7-9ecf-4784-870d-1a96039ee77a.png)

system version:
```
Linux 6.0.11-x64v1-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Sat, 03 Dec 2022 04:26:21 +0000 x86_64 GNU/Linux
```

proxy settings:

Bug occurred with or without HTTP proxy, looks like the traffic does not go through proxy.

# Note
- Images could be fetched normally from official site like: https://p3.music.126.com
- Search engine works well, music could be searched and listed out
    
![图片](https://user-images.githubusercontent.com/44747719/207801492-66b7fd34-af1d-451e-a630-ecf6dccbfaf1.png)
- curling local music server output:
```
curl -vvv http://localhost:35307
*   Trying 127.0.0.1:35307...
* Connected to localhost (127.0.0.1) port 35307 (#0)
> GET / HTTP/1.1
> Host: localhost:35307
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 418 I'm a teapot
< Date: Thu, 15 Dec 2022 07:43:30 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
@see https://tools.ietf.org/html/rfc2324%      
```
```
❯ curl -vvv 'http://localhost:35307/music?id=29719536&quality=ex'
*   Trying 127.0.0.1:35307...
* Connected to localhost (127.0.0.1) port 35307 (#0)
> GET /music?id=29719536&quality=ex HTTP/1.1
> Host: localhost:35307
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 15 Dec 2022 07:54:38 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"message":"request to https://m7.music.126.net/20221215161906/<truncated> failed, reason: net::ERR_CONNECTION_RESET","type":"system","errno":"ERR_CONNECTION_RESET","code":"ERR_CONNECTION_RESET"}%      
```
- wget music location above directly returns file successful

**Comment by rocka** [comment]
Do you have any proxy-related environmet variable set? eg. `all_proxy` `http_proxy` `https_proxy` `SOCKS_SERVER` . Since we are using [`electron-fetch`](https://github.com/arantes555/electron-fetch) to perform http requests in the main process, it should follow those proxy settings. What happens if you unset all of them?

Also without any proxy settings, I didn't encounter any problems myself.

**Comment by ClSlaid** [comment]
It's found when curling cloud music sites with IPv6 enabled, connections will be reset:
![图片](https://user-images.githubusercontent.com/44747719/207915631-19406058-94a0-49d1-ba32-9cead1ba5ef5.png)
I'll try with IPv6 disabled then.

**Comment by rocka** [comment]
You can run the app with `env DEBUG='*' electron-netease-cloud-music` to get verbose logging, I've almost forgot that...

**Comment by ClSlaid** [comment]
After disable the IPv6, the player worked successfully!

I think this could be fixed by making the player prefer IPv4 over IPv6.

**Comment by rocka** [comment]
Maybe I can add a switch for that, though it works fine on my machine with IPv6 enabled.

**Comment by ClSlaid** [comment]
> Maybe I can add a switch for that, though it works fine on my machine with IPv6 enabled.

You can test with `curl -6`. On my computer, these requests fail into `CONNECTION_RESETS`.

**Comment by rocka** [comment]
I can confirm it works with `curl -6`. And in your second screenshot with devtool's Network tab, it shows an IPv6 address as "Remote Address", so in theory it should work with IPv6.

**Comment by ClSlaid** [comment]
> I can confirm it works with `curl -6`. And in your second screenshot with devtool's Network tab, it shows an IPv6 address as "Remote Address", so in theory it should work with IPv6.

Hello, now I moved to other city and the problem seems solved. This may be my local ISP to blame. I'll close this issue since I can hardly provide more information. Thanks for your kindness help and robust software.

Best regards.
