### ISSUE TITLE
[BUG] 私人 FM 播放完时从头播放

### ISSUE THREAD

**Issue by StephanoGeorge** [Rocket1184/electron-netease-cloud-music#152]
私人 FM 播放完最后一首（此时历史记录达到最大长度 150 首）后没有新的歌曲，从历史记录开头第一首播放。

期望：在播放到末尾时请求新歌曲。可以观察到大部分情况下会自动请求。

在能正常加载歌曲时打印的日志：

```
vue.runtime.esm.js:6831 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22
```

未自动加载新歌曲发生在此事件后，但两者之间时似乎仍正常加载过歌曲（记不清）。

网络请求均为 2xx。

安装方式：`yay netease`。

**Comment by rocka** [comment]
之前是写过私人 FM 播放到最后一首时，通过 API 获取新的歌曲（通常是 3 首），如果超出最大数量，就删掉最旧的，然后让“正在播放”的指针前移“新获取到的歌曲”的数量。而且这里有一个去重的处理，如果新获取到的某首歌曲已经在列表中出现过了，那么就不会再次把它加进列表

https://github.com/Rocket1184/electron-netease-cloud-music/blob/9f23ee2e4cb951d9e88275d0ddb2bec579512c41/src/renderer/store/modules/radio.js#L29-L44

但在极端情况下，如果新获取到的 3 首歌都在列表中出现过，那么将不会有新歌被加进列表，按照正常的播放列表逻辑，最后一首歌播完之后就跳到了第一首。

解决办法大概只能是多重试几次了，私人 FM 返回重复歌曲的情况也不能算是很少见了 ...
