### ISSUE TITLE
Ubuntu无法使用该软件

### ISSUE THREAD

**Issue by pyqi-Bilibili** [Rocket1184/electron-netease-cloud-music#153]
已添加repo，但是并没有这个包
![图片](https://user-images.githubusercontent.com/56102825/211457237-7453714c-d8c6-4a84-9f7b-55130f737ae0.png)

**Comment by rocka** [comment]
https://github.com/coslyk/debianopt-repo 是一个 Debian 仓库，不知道 Ubuntu 能不能用。建议去那边提个 issue ，我这里没办法解决。
