### ISSUE TITLE
[Feature Request] 定时更新动态歌单的图片和标题

### ISSUE THREAD

**Issue by zetako** [Rocket1184/electron-netease-cloud-music#154]
网易云存在“动态歌单”，会定时更新歌单内的数据；例如[私人雷达](https://music.163.com/#/playlist?id=3136952023)，这个歌单会每天更新。

如果一个程序运行超过一天，那么“歌单”侧边栏的该歌单仍会表现为第一天的标题和图标，但是详情页内则会正常更新。如图所示：

![Screenshot_20230203_165943](https://user-images.githubusercontent.com/54136740/216557597-2c8dc40c-98bc-437c-9ca9-9ada311b124d.png)

希望可以为这类歌单添加定时刷新的机制，使其能正确地显示在侧边栏中。

**Comment by rocka** [comment]
这种“动态歌单”的更新时间是固定的么？如果像“私人 FM”那样有个固定的刷新时间，就比较方便了

**Comment by rocka** [comment]
从返回的数据来看，“私人雷达”有几个特殊的字段：

```
                       私人雷达  //  一般其它歌单
gradeStatus:          "OPENED"  //   "NONE"
officialPlaylistType: "ALG_OP"  //    null
specialType:           100      //    0   (“<用户名>喜欢的音乐”为 10 )
updateFrequency:      "每日更新" //    null
```

虽然有 updateFrequency ，但这大概是给 UI 上展示，而不是用来计算的吧 ...

**Comment by zetako** [comment]
> 从返回的数据来看，“私人雷达”有几个特殊的字段：
> 
> ```
>                        私人雷达  //  一般其它歌单
> gradeStatus:          "OPENED"  //   "NONE"
> officialPlaylistType: "ALG_OP"  //    null
> specialType:           100      //    0   (“<用户名>喜欢的音乐”为 10 )
> updateFrequency:      "每日更新" //    null
> ```
> 
> 虽然有 updateFrequency ，但这大概是给 UI 上展示，而不是用来计算的吧 ...

在安卓客户端上确实能看到“每日更新”，在其他官方歌单的该位置还有“每周五更新”，“不定期更新”等；这个属性大概确实只影响UI显示，可能要看看`officialPlaylistType`与更新频率是否匹配。这些歌单都是APP内歌单的“官方”分类找到的。

- “每周五更新”：
  - https://music.163.com/#/playlist?id=5358179958
  - https://music.163.com/#/playlist?id=5395488578
- “不定期更新”：
  - https://music.163.com/#/playlist?id=8254513734
  - https://music.163.com/#/playlist?id=8533110203

**Comment by rocka** [comment]
这些歌单的 `specialType` 均为 `100` ， “每周五更新”的这两个 `officialPlaylistType` 的值为 `"ALG_OP"`，“不定期更新”的则为 `"OP"`，感觉似乎没有很好的办法来判断。似乎只能在打开详情页面的时候，顺便更新一下侧边栏里的数据了。

**Comment by rocka** [comment]
should be fixed by 73c9c3b
