### ISSUE TITLE
[Question] Heroku Releases Server down

### ISSUE THREAD

**Issue by Fira50128** [Rocket1184/electron-netease-cloud-music#155]
用来给其它发行版和macOS提供带electron的[下载网站](https://ncm-releases.herokuapp.com/)寄了。
提示**Application error**。

asar包倒是还能在Github下载，虽然不影响我自己使用，但应该会有人需要带electron的整合包的吧。大大们要不修一下？

**Comment by rocka** [comment]
Heroku 已经不提供免费服务了，该迁移到 GitHub Actions 了 ...

不过说白了，整合包不过就是把 electron 和 asar 用 zip 压在一起而已，参考 https://github.com/Rocket1184/electron-netease-cloud-music/issues/108 的方法下载一下 electron 就可以了，而且淘宝的 electron 镜像大概会比七牛的免费 CDN 要更快

**Comment by Fira50128** [comment]
好的，谢谢大大。

防止有人需要，这里再发一个当时的[归档网页](https://web.archive.org/web/20220902235330/https://ncm-releases.herokuapp.com/)吧。
https://web.archive.org/web/20220902235330/https://ncm-releases.herokuapp.com/
归档页面的下载链接目前还能正常使用。

**Comment by rocka** [comment]
终于有时间来迁移这个了，新的下载页面在这里： https://dl.encm.cf
顺便 CI 也从 Travis 迁移到了 GitHub Actions ，这几天应该会发一个新版本
