### ISSUE TITLE
Arch Linux 下 Pacman 命令找不到包😖

### ISSUE THREAD

**Issue by Ya2gLu** [Rocket1184/electron-netease-cloud-music#157]
![image](https://github.com/Rocket1184/electron-netease-cloud-music/assets/48912522/bdf5371d-a8ef-42e5-87a3-2b5b48d4edde)
如图所示
系统：Arch Linux 
![image](https://github.com/Rocket1184/electron-netease-cloud-music/assets/48912522/0338a3d7-cb07-43e9-91e1-8ddf9380def5)

**Comment by rocka** [comment]
需要添加 archlinuxcn 仓库 https://www.archlinuxcn.org/archlinux-cn-repo-and-mirror/
