### ISSUE TITLE
自动更新签到状态？

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#17]
可能是个比较小众的需求。。现在签到状态不会自动刷新，换日之后必须关掉再开才能再次签到。能不能记录上次签到的日期，隔几分钟检查一下，发现日期变了就刷新一下状态。（能顺手自动签到更好。。）

**Comment by rocka** [comment]
其实是有签到状态检查的，不过只有在每次启动程序的时候才会检查。自动签到也可以做个选项。

**Comment by rocka** [comment]
都完成了，设置里面添加了自动签到的选项。来下载最新构建版本测试吧 https://ncm-releases.herokuapp.com/

**Comment by ylxdzsw** [comment]
赞！
