### ISSUE TITLE
[Feature Request] 暗色模式增强

### ISSUE THREAD

**Issue by su226** [Rocket1184/electron-netease-cloud-music#172]
1. 根据 [Material Design 规范](https://m2.material.io/design/color/dark-theme.html#ui-application)，暗色模式的 AppBar 应该是灰色而非主题色。
> In a dark theme, the surface of the top app bar uses a dark color instead of a primary or secondary color.
2. 亮色模式的主题色/强调色在暗色模式下不太明显（在自动亮色/暗色模式下），建议单独增加暗色模式的主题色/强调色设置。
3. 由于 Snackbar 的颜色与背景颜色相反，Snackbar 的关闭按钮颜色也不太明显，建议 Snackbar 的关闭按钮使用黑色或白色，不使用主题色，类似于 [MUI](https://mui.com/material-ui/react-snackbar/) 的做法。

**Comment by rocka** [comment]
I don't care about material design 2 or 3.
