### ISSUE TITLE
按空格暂停播放中的 MV 或收藏的视频

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#18]
添加按下空格可以暂停和播放视频的支持。

**Comment by rocka** [comment]
在 https://github.com/Rocket1184/electron-netease-cloud-music/commit/6511ddba21ddd06de81e0d30239fc29b0a4f854b 添加了，顺便加上了鼠标滚轮控制音量，操作逻辑跟 https://github.com/Rocket1184/electron-netease-cloud-music/issues/13#issuecomment-466946969 是一样的

**Comment by rocka** [comment]
closed via [v0.8.3](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.3)
