### ISSUE TITLE
问几个关于cookie的问题

### ISSUE THREAD

**Issue by xs9888** [Rocket1184/electron-netease-cloud-music#181]
1、登录cookie的有效期是多少天？
2、登录cookie过期后，还可以刷新登录状态吗？
3、刷新登录状态接口返回的是新的cookie还是说只是更新旧cookie的有效期，旧cookie还可以继续用？我这边刷新后cookie没有MUSIC_U这个参数

**Comment by rocka** [comment]
最佳答案：我不知道

只有网易自己知道
