### ISSUE TITLE
账号被风控

### ISSUE THREAD

**Issue by LAST7** [Rocket1184/electron-netease-cloud-music#182]
最近网易云账号被冻结了，问了一下客服说是有使用第三方平台登录

先是不断被登出，重设密码才能登录。往复几次之后就被冻结了。

**Comment by AllenWu233** [comment]
似乎是所有用网页端API的登录请求都会被封号，Yes Play Music也有同样的问题，详见https://github.com/qier222/YesPlayMusic/issues/2310

**Comment by rocka** [comment]
我倒是有一套 eapi 的注册登录接口，但是一直没空 commit 上去 ...
