### ISSUE TITLE
点歌单中的一首歌，播放页面是不是应该添加一个返回？

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#19]
![screenshot_20190224_093547](https://user-images.githubusercontent.com/9500049/53293901-a67b1c00-3817-11e9-8aee-d6a9371131f0.png)

不然，要点击到个性推荐，在找到那个歌单。

就是播放歌曲页面是不是添加一个返回上一步的按钮？

**Comment by rocka** [comment]
按一下左下角进度条左边的的专辑封面图片就可以收起播放界面了，在按一下可以展开。

所有界面都可以收起/展开播放页面
