### ISSUE TITLE
More than 1000 songs?

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#22]
我的播放列表有超过1000首，但是只能显示前1000.官方客户端的话,滑到底之后继续滑可以加载出后面的,不知道网页版做不做得到.

**Comment by rocka** [comment]
这个问题我正好前几天研究过。网页版只能显示前 1000 首，网易给的 API 里面似乎只有 limit 这个字段是有效的，没有 offset，也不能控制分页。

但客户端是怎么显示超过 1000 首以后的歌曲的的呢？经过抓包证实客户端的 API 也只能显示前 1000 首。但有一个根据歌曲 ID 批量查询歌曲信息的功能，这时候客户端就会把很多歌曲的 ID POST 出去，用来获取剩下的歌曲信息 ... 看到这里的时候我的内心是崩溃的

当然实现这个功能是必要的，不过可能需要鸽一段时间让我来找到更加优雅的方式。

顺便一提， Android 客户端加载一个大于 1000 首的歌单时，这时候如果点击 <kbd>播放全部</kdb> ，那只能播放前 1000 首。不过如果手动把 1000 首以后的歌添加到播放列表，还是能够添加进去的。

所以还有一个问题，加载大于 1000 首的歌单的时候，要一起把所有的歌曲加载出来，还是在翻页的时候去动态获取？

**Comment by ylxdzsw** [comment]
所以其实列表的API可以获得【所有歌曲id】和【前1000首歌曲的信息】，然后有另外一个API可以获得【指定id的歌曲信息】？这样的话我觉得不如自己缓存一个【id->歌曲信息】的表，然后也别用它那个前1000首的API了，每次就读取歌单的id列表，然后自己查对应的信息，cache miss了再用那个查询的API查一下。不知道我有没有哪里没理解对。

**Comment by rocka** [comment]
> 列表的API可以获得【所有歌曲id】和【前1000首歌曲的信息】，然后有另外一个API可以获得【指定id的歌曲信息】

就是这样

> 缓存一个【id->歌曲信息】的表，然后也别用它那个前1000首的API了，每次就读取歌单的id列表，然后自己查对应的信息，cache miss了再用那个查询的API查一下

这是个好主意，也可以加快歌曲列表的加载速度

**Comment by rocka** [comment]
终于~~咕~~出来了 😂

![image](https://user-images.githubusercontent.com/13914967/57784647-d4ab3080-7762-11e9-93c4-f9cf9c1bc6dd.png)

**Comment by rocka** [comment]
播放列表也可以超～～～大，比官方客户端还要好用（确信

![image](https://user-images.githubusercontent.com/13914967/57784806-22279d80-7763-11e9-919d-398b7b6664bb.png)

**Comment by ylxdzsw** [comment]
超～～～赞！快push上来啊

**Comment by rocka** [comment]
刚 push 了[一大堆更改](https://github.com/Rocket1184/electron-netease-cloud-music/compare/3fbdaca..f1d5813)，包括支持 1000 首以上的歌单，还有搜索播放列表中的歌曲等等 ... 可能很 buggy 或者有性能问题，但总之先测试一下看看～

**Comment by rocka** [comment]
https://github.com/Rocket1184/electron-netease-cloud-music/commit/c239235b2d4276453e078adcc0c55df0039d3235 修复了歌单只能看不能操作的 bug 😂

大概可以关了
