### ISSUE TITLE
[Bug] 播放歌曲与显示曲目不符合

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#24]
触发条件：未知
OS： Linux
版本：0.8.3

------

我这里有个录屏（7d后过期，在宾馆录的，所以录制环境很差，请降低音量）:
https://send.firefox.com/download/2b4ec14418/#4IfDhMsrFWgIJt1D0W8Bhg

**Comment by rocka** [comment]
估计可能是私人 FM 切换时候的问题 ... 不过不能稳定复现的话也不知道从哪下手了 = =

**Comment by Gabirel** [comment]
我大概的操作是：
1. 在私人FM上发现了一首歌，加入了收藏
2. 在收藏里点了好几次，也听了好几个
3. 又切换到私人FM里找之前喜欢的那个歌，切过好多个歌

不知道这个对调试有没有帮助。
（PS：那个歌是多语言的切换的，我觉得可能跟这个没影响，大概率跟缓存有影响，我用的老笔记本）

**Comment by Gabirel** [comment]
再一次触发的操作：
在主界面，疯狂按了删除（不喜欢）。
程序每次加载3首歌，点到了最后一个的时候，再点删除，就会重新回到三个一队的第一个，继续重复播放。然后疯狂按删除（不喜欢），然后就跑到了我的列表的第一个（Yes！ Love）。

![image](https://user-images.githubusercontent.com/12933851/54746586-84eb3580-4c07-11e9-8898-960645be053e.png)
![image](https://user-images.githubusercontent.com/12933851/54746650-aea45c80-4c07-11e9-8684-1f664ec9dba7.png)

现在的另一个情况就是，下面的横栏和播放的歌词那栏不同更新了。感觉程序逻辑已经不正确了（虽然可以继续播放，但是GUI已经脱疆啦）。

**Comment by rocka** [comment]
> 在主界面，疯狂按了删除（不喜欢）。
程序每次加载3首歌，点到了最后一个的时候，再点删除，就会重新回到三个一队的第一个，

按下 <kbd>不喜欢</kbd> 这个按钮的时候，会先向调用 API 向网易发送不喜欢的请求，然后把歌曲切到下一首。我这边测试的结果也是一样的，如果疯狂 <kbd>不喜欢</kbd>，在新的歌曲加载出来之前，会直接回到列表的第一首歌，而不是三个一队的第一个。而且也确实没有写三个一队这样的代码，只是每次请求私人 FM 的时候大概率会返回三首。

> 现在的另一个情况就是，下面的横栏和播放的歌词那栏不同更新了。

这个情况我并没能复现 ...

**Comment by Gabirel** [comment]
> > 现在的另一个情况就是，下面的横栏和播放的歌词那栏不同更新了。

> 这个情况我并没能复现 ...

至于这个，我也不知道怎么复现。因为上一次出现这个问题也是这种情况。经过了几个小时，这个播放的下面栏仍然没有“更新”，感觉它已经不会再正常了，除非我杀掉这个进程重来一遍。

**Comment by rocka** [comment]
我在尝试修复 #29 的时候偶然复现了这个 bug，现在想来应该就是私人 FM 存储的历史超出限度后处理有问题

**Comment by rocka** [comment]
closed in [`v0.8.5`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.5)
