### ISSUE TITLE
[Feature Request] 双击或者长按音量图标静音

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#25]
Request: 能够在主界面双击或者长按音量图标静音，然后再次重复操作可以恢复原来的音量

原因：我发现我经常需要会出现这种情况：我不想要暂停，但是我需要它安静下来不发出声音。由于不能直接设置静音，需要自己手动拉音量条；然后再拉回到一个适当的值。很麻烦。

**Comment by rocka** [comment]
直接静音可以按鼠标中键（滚轮），我觉得双击这个操作不太优雅

**Comment by Gabirel** [comment]
那`长按`？用中键是可以，但是我需要记忆住我现在的音量值大小，等我不静音了我又需要精确调到那个值。所以觉得可以记住那个值，这样静音就很方便而且优雅

**Comment by rocka** [comment]
中键是可以记忆静音之前的值的

**Comment by Gabirel** [comment]
![deepin-screen-recorder_electron-netease-cloud-music_20190316170931](https://user-images.githubusercontent.com/12933851/54483255-34807a80-488b-11e9-9be8-251227582dc0.gif)

这个GIF里是连续性的，但是我理解的“记忆”的是那种“断崖式”的，比如，45->0，0->45的断崖变化。不知道是我理解有问题还是我表述不清楚

**Comment by rocka** [comment]
如果你自己把音量从 45 一点一点减小到 0 那当然是没办法记住的 … 我指的记忆是，把鼠标放在音量图标上，然后 **点击** 鼠标中键（aka auxclick），这时候会进入静音状态，音量滑动条变成灰色但是音量数值保持不变。然后再次中键点击音量图标，退出静音状态，音量恢复为之前的数值。

**Comment by rocka** [comment]
突然发现 `auxclick` 这个事件的也会同时响应鼠标右键的点击，具体到这里的话，就是鼠标右键点击音量图标也会触发静音的操作。这下应该方便许多了吧。

**Comment by Gabirel** [comment]
这个真的方便很多，至少比中键按着爽。按了几十下，哈哈哈，很方便
