### ISSUE TITLE
[Feature Request] 分享功能

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#26]
在使用的过程中有时听到很有意思的歌，找了半天分享，发现没有分享功能。

如果直接把歌名发给对方，对方又需要搜索又需要复制歌曲名，有点麻烦。
要是能够拷贝**歌曲的链接**是最好的了。

另外：在播放栏目，不能选择歌曲名和歌手名来复制是故意这么设计的吗？
![image](https://user-images.githubusercontent.com/12933851/54472719-0443c800-4808-11e9-88c7-af299b8433c4.png)

**Comment by rocka** [comment]
唉。能选择的话会有人嫌太粗糙不够原生，但是不能选的话有时候用到又会觉得麻烦；我也很纠结的。

**Comment by Gabirel** [comment]
那不能复制就算了吧。如果能够分享，这个功能也可以通过打开主界面来复制。

**Comment by Gabirel** [comment]
我觉得可以有类似于手机版分享的那种自动识别的页面就行了。如果是其他应用里面，有个
`歌曲名+歌手+专辑名+URL`就够啦。
![1767410552](https://user-images.githubusercontent.com/12933851/54473045-900c2300-480d-11e9-9b6f-d62596439ff6.jpg)

**Comment by rocka** [comment]
这种在 IM 工具里面预览分享链接是他们的分享 SDK 的功能吧，我觉得可能没法做到这些 ... 至少 Linux 和 Windows 桌面都没有通用的分享接口，只能实现显示一些文本然后复制到粘贴板这样的操作了。

**Comment by Gabirel** [comment]
那也可以吧。有URL其实就是最基础的，其他的比如歌曲名有就有，没有也不要紧。毕竟还是能够定位是第一要务。

**Comment by rocka** [comment]
closed in [`v0.8.5`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.5)
