### ISSUE TITLE
[Feature Request] 添加私人FM自动开启的设置

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#27]
不知道能不能加一个“私人FM自动开启”并自动播放的功能。（我看有自动签到功能，我觉得提这个Request应该不过分吧？不知道能不能加一个）

----

另外，私人FM的播放顺序能够逆序吗？我每天打开私人FM列表都是那首歌，然后看着挺无聊的。况且，又不需要用到。就不能够逆序显示吗？这样找也方便也不会天天重复。（逃

**Comment by rocka** [comment]
这个可以有

**Comment by rocka** [comment]
我觉得 自动开启私人 FM 这样的做法有点太一刀切了，不如改成记住退出时的播放状态，比较符合直觉。

然后再加一个 启动时开始播放 的选项。

**Comment by rocka** [comment]
然后播放顺序逆序这个问题，如果播放列表里面的上一首/下一首方向不一致的话感觉很别扭 ... 我打算只是私人 FM 页面逆序显示（最新在最上面），播放列表里面还是顺序（最新在最上面）

**Comment by Gabirel** [comment]
> 我觉得 自动开启私人 FM 这样的做法有点太一刀切了，不如改成记住退出时的播放状态，比较符合直觉。
> 
> 然后再加一个 启动时开始播放 的选项。

我的意思其实是在设置里开启一个这样的设置，类似于“自动签到”的开关。不是说完完全全

**Comment by rocka** [comment]
done in [`v0.8.4`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.4)
