### ISSUE TITLE
[Bug] 私人FM中播放列表的歌曲经常重复播放

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#29]
这个“经常”是真的是经常，基本上每天听每天都会遇到，每个上午下午都会遇到

**Comment by rocka** [comment]
是重复一首歌还是重复整个列表呢？虽然 API 可能获取到重复的歌曲，但这边已经做过去重处理了

**Comment by Gabirel** [comment]
我觉得不是API获取的重复，是程序的判定的问题。

每次重复的就是会在列表里往前3个左右（一次API的请求）。就是在经常点`不喜欢`就会发生这个现象。

**Comment by rocka** [comment]
我大概明白是哪里的问题了 ... 私人 FM 播放历史的保存上限是 150 首，如果超出的话，按照设计，会先把新获取到的歌曲 push 到列表里，然后再把多出来的从最前面删掉。这么想来可能是这里的逻辑有问题

**Comment by rocka** [comment]
closed in [`v0.8.5`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.5)

**Comment by Gabirel** [comment]
在`v0.8.5`里面，私人FM还可以保存150首歌以上吗？我的私人FM界面的歌曲应该不止150个，起码有300个。这个也是正常的吗？

**Comment by rocka** [comment]
@Gabirel 当播放到私人 FM 列表最后一首的时候，开始获取新的歌曲，这时候会把多余的删除掉，只保留最近获取的 150 首。以后的每一次获取新歌曲之后都会这么做。
