### ISSUE TITLE
[Feature Request] 在Tray Icon的下拉菜单添加静音的Toggle

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#30]
这个tray icon简直太好用了。十分赞！

但是，我经常需要单个静音程序，我每次静音都要点开程序主界面，再用鼠标中键去点静音（说实话，中键真的不好按），然后再隐藏掉主程序界面。解除静音同样需要重复这样的步骤。

这个步骤能不能简化成在tray icon的下拉菜单里？这样每次需要对程序静音，只需要点开tray icon下来菜单就行了。
我对electron不是很了解，不知道能不能在下拉菜单里放一个toggle，要是不能可以用两行（当有声音的时候，`静音`设置成enabled，`取消静音`设置为disabled；vise versa）
我看`播放/暂停`也可以有两种state，我想，这个`静音/取消静音`也可以有两种state

（与本issue的主题无关）有个小想法：
在tray icon的下拉菜单里面，会有三行内容（歌曲名、歌手名与专辑名），反正这三个都是点击了没有反应。或许可以把它们利用起来？点击他们就可以把分享功能的链接给直接复制到剪贴板上。（虽然我目前还没有过这种操作场景过，所以只是一个小想法）

**Comment by rocka** [comment]
> 这个步骤能不能简化成在tray icon的下拉菜单里？这样每次需要对程序静音，只需要点开tray icon下来菜单就行了。

可以用类似 `喜欢` 的操作，把 `静音` 也做成一个 checkbox

> 在tray icon的下拉菜单里面，会有三行内容（歌曲名、歌手名与专辑名），反正这三个都是点击了没有反应。或许可以把它们利用起来？点击他们就可以把分享功能的链接给直接复制到剪贴板上。

这真的是一个不错的想法 🎉

**Comment by rocka** [comment]
done in https://github.com/Rocket1184/electron-netease-cloud-music/commit/39c814d7e88445e36df369ff2d8d388f41584267

<img src=https://user-images.githubusercontent.com/13914967/55558522-da9f0200-571e-11e9-834a-b87d5ae86f34.png width=392>
