### ISSUE TITLE
[Feature Request] 添加电台栏目

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#31]
网易云电台栏目的存在意义：（个人看法）

网易云的电台的栏目是十分适合给那种自创型歌手的，也包括了鬼畜和翻唱。（避免侵权）

比如N多大佬的鬼畜作品，还有很多up主或者其他人的翻唱歌曲都一般会放在这个上面。感觉没了这个，😳我感觉我鬼畜都听不了了，只能很麻烦地打开网页版再去听。(我这里也有例子，不过我为了避“宣传”嫌，就不提。如果你需要这种电台的例子，我可以贴出来)

如果你要说这个东西用的人多吧，其实也不多。但是你要说用的人少吧，我觉得也不少。毕竟很多没有版权的歌曲也会被放在电台栏目里。

所以，如果能有API可以实现，是否可以考虑加个这个Feature呢？

**Comment by rocka** [comment]
前几天我也发现有些歌曲只能在电台里面听到 ... 这个还是挺有用处的

**Comment by sxyugao** [comment]
需要 +1，像我这种经常听电台的人感觉很难受

**Comment by rocka** [comment]
现在差不多能播放了，不过还有很多问题。

![image](https://user-images.githubusercontent.com/13914967/58708115-72e8f880-83e9-11e9-90a1-9580229676ea.png)

主播电台的一系列 API 与歌曲的 API 都不一样。每一期电台节目对应着一首歌曲，但是评论又没有挂在对应的歌曲下面 ... 处理起来有点烦。

官方客户端的做法是把电台单独摘出来，播放电台的时候就把当前的播放列表替换掉。但我的想法是让电台节目和一般歌曲在播放列表中共存，这样的话还得在播放列表操作的时候再做些判断 ...

对这个功能有什么想法吗？ @Gabirel @sxyugao

**Comment by Gabirel** [comment]
如果可以把电台音乐和一般播放列表整合起来的话，那肯定是最好的。

平时用官方客户端就觉得每次找电台里的歌曲就挺麻烦的，如果可以放在一般列表里，那就会省掉很多的切换操作

**Comment by sxyugao** [comment]
为什么我找不到电台入口。。

**Comment by rocka** [comment]
@sxyugao 因为还没完成 ... 这个是我开发环境里面的截图 😅

想问一下对这个功能有没有什么特别的需求

**Comment by Gabirel** [comment]
突然想到，如果「电台」功能发挥好，就可能需要把「用户」功能补全。难道搜索电台的方式就是通过搜索电台的电台名？不是通过用户的页面里选的？

**Comment by rocka** [comment]
@Gabirel 目前的计划是先把订阅过的电台播放做出来，然后搜索电台名和用户都会有的

**Comment by rocka** [comment]
啊 没想到又鸽了这么久 ...

[`v0.8.13`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.13) 版中新增了电台版块，目前只能从 我的收藏->电台 进入。只能查看已收藏的电台，超过 500 期节目的电台只能查看最新的 500 期，不能对电台节目进行评论或者点赞 ... 总之功能还很残废。

不过起码能播放了，而且电台节目与一般歌曲是可以混在一个播放列表里面的。

**Comment by Gabirel** [comment]
@rocka 不好意思，最近有点忙。这个电台没有显示不出来评论的功能么？原曲是700多的评论，现在一个评论都没有。

**Comment by rocka** [comment]
对，还不能看电台的评论 ...

**Comment by rocka** [comment]
现在（[`v0.8.14`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.14)）可以 看评论 以及 复制分享链接 了，顺便歌词的位置显示节目简介，就差点赞了 ...

**Comment by rocka** [comment]
[`v0.9.0`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.0) 中新增了电台节目点赞的功能，这个 Issue 应该可以关掉了
