### ISSUE TITLE
[Feature Request] 音乐下载

### ISSUE THREAD

**Issue by sshwy** [Rocket1184/electron-netease-cloud-music#32]
本人manjaro用户，很喜欢electron-netease-cloud-music的界面，也期待待开发的功能，只是希望能不能增加一个音乐下载的选项啊～毕竟呢萌的MV都是可以下载的啊
再次表达对开发者大大的支持啊

**Comment by rocka** [comment]
其实听到的歌曲都已经缓存在本地了，再顺便加个下载应该也没那么麻烦

**Comment by Core00077** [comment]
不能下载是版权问题啊，这是红线。倒是可以绕过一下，加一个本地音乐播放的功能，然后网易云本身允许缓存的音乐拷电脑上播放即可。

**Comment by rocka** [comment]
#96 终于合并进来了 😂 不过还有很多改进的空间，比如显示已下载歌曲的列表，管理已下载歌曲，甚至匹配本地音乐的功能 ... 但这个 Issue 可以暂时先关闭了 😅
