### ISSUE TITLE
[Feature Advice] 调整Tray Icon下拉菜单的按钮事件顺序

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#33]
现在的按钮顺序是这样的：
![image](https://user-images.githubusercontent.com/12933851/56471521-28896900-6486-11e9-80fa-933f5013321d.png)

Advice：希望那个 `喜欢` 和 `不感兴趣` 的按钮事件可以放在最上面（取代 `显示主界面`和 `退出`）

众所周知“二八定律”，这个定律也同样适用于这个点击的习惯。我80%的点击行为都是 `不感兴趣` 和 `喜欢` ，只有很少的一部分点击行为是需要显示界面和退出的。但是每一次点击 `不感兴趣`我都要把光标往下拉很多，经常会因为太快又距离太长点错了（老是点错了喜欢，很会影响私人FM推荐的歌曲，有点讨厌的还是）。

所以建议希望可以把 `喜欢` 和 `不感兴趣` 的按钮事件上调到最上面

**Comment by rocka** [comment]
这样看起来确实有些不方便，需要调整一下 ...
