### ISSUE TITLE
[Feature Request] 热键需求

### ISSUE THREAD

**Issue by sxyugao** [Rocket1184/electron-netease-cloud-music#36]

**Comment by rocka** [comment]
应用内的快捷键，还是后台也能响应的全局快捷键？还有哪些功能想要用快捷键触发呢？

自从有了 MPRIS ，我都用笔记本键盘上的媒体按键控制播放/暂停和切歌 …

**Comment by sxyugao** [comment]
> 应用内的快捷键，还是后台也能响应的全局快捷键？还有哪些功能想要用快捷键触发呢？
> 
> 自从有了 MPRIS ，我都用笔记本键盘上的媒体按键控制播放/暂停和切歌 …

是指全局的快捷键

其实是因为快学考了没时间折腾 Arch 的多媒体键。。

**Comment by sxyugao** [comment]
已自行添加快捷键了
