### ISSUE TITLE
[bug] main process exception when track duration is 0

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#38]
![Screenshot from 2019-05-05 14-13-51](https://user-images.githubusercontent.com/7145046/57189354-756a4680-6f40-11e9-842b-fea0972e6857.png)

It happens during switching songs (I'm using random play).

**Comment by rocka** [comment]
虽然带了 source map，但是没有配置，报错的时候还是不知道源码的位置 ... 难受

**Comment by rocka** [comment]
What's the version of ElectronNCM and Electron?

Did it crash when you manually switch to next song, or automatically when current song playback ends?

**Comment by ylxdzsw** [comment]
版本就是aur和arch源上最新的。自动切换的时候出错的，切换的时候窗口是最小化状态。

**Comment by rocka** [comment]
当时在听的是哪个歌单？

**Comment by ylxdzsw** [comment]
Hi, it was my favorite: https://music.163.com/#/playlist?id=6362064 . I think there is nothing special (except for it has more than 1000 songs?) in the playlist.
I tried to reproduce this issue by rapidly switching songs but it never happens again.
By the way I did some sourcemap looking-up. It shows that the whole stacktrace are inside ./node_modules/dbus-native/lib/marshall.js .

**Comment by rocka** [comment]
找到原因了。

![image](https://user-images.githubusercontent.com/13914967/57305917-6a680f80-7114-11e9-8154-e93f71f15b62.png)

在把从网易云音乐 API 里面取到的数据转成定义好的模型类的时候，有一首歌的 `dt` 值是 `0` ，然后就取到了 `duration` ，结果后者并未定义，是 `undefined` 。

> 这里这么写的原因，是网易云音乐 API 里面返回的有些相同的实体对象，有些字段的名称却不同 ...

https://github.com/Rocket1184/electron-netease-cloud-music/blob/3fbdacaef735b00b1c81c00c2bb8294d8052d8c1/src/renderer/util/models.js#L29

然后 `undefined` 的 duration 值被传到主进程，乘以 `1e3` 之后变成 `NaN`，没有做任何的类型检查就传给 dbus-native ，但 `NaN` 没法被当作一个数字，所以直接崩掉了。

https://github.com/Rocket1184/electron-netease-cloud-music/blob/3fbdacaef735b00b1c81c00c2bb8294d8052d8c1/src/main/mpris/mpris-native.js#L180

**Comment by ylxdzsw** [comment]
666666，这都找出来了
