### ISSUE TITLE
搜索歌词、歌曲报错。

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#39]
> 出错了...400参数错误。

很抱歉，梯子坏了，无法上传图片。

**Comment by rocka** [comment]
切换一下搜索页面的 tab 就好了 … 马上会修复

**Comment by roachsinai** [comment]
确实。。点一下歌手，视频什么的确实好了。感谢。

**Comment by rocka** [comment]
fixed via https://github.com/Rocket1184/electron-netease-cloud-music/commit/fd9445548088362c296e6cd0ffb90887e34589f9
