### ISSUE TITLE
界面变成紫色了。。。。

### ISSUE THREAD

**Issue by a-wing** [Rocket1184/electron-netease-cloud-music#4]
官方红那 ->_->

**Comment by Rocket1184** [comment]
本来我也想用官方红色的，不过紫色看习惯了还挺好看的 🤣 

或许可以加个换主题的功能 ...

**Comment by rocka** [comment]
[`v0.5.2`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.5.2) 添加了更换主题颜色的功能，还有暗色主题支持

这个 Issue 终于可以关掉了 :laughing:
