### ISSUE TITLE
不能自动跳到下一首

### ISSUE THREAD

**Issue by mengyaoss77** [Rocket1184/electron-netease-cloud-music#40]
一首歌放完以后，进度停留在这首歌的最后，播放状态为“播放中”（UI显示暂停键）
必须手动点“下一首”的按钮才行

**Comment by rocka** [comment]
使用的是哪个应用版本？每次都能复现吗？应用设置->启动开发者工具 看看控制台有无报错？

**Comment by mengyaoss77** [comment]
这两天好像更新版本了，目前是：
版本号
Electron: 4.1.4
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.30-electron.0

系统是manjaro kde。
目前的版本不能拖进度条了，一点击进度条进度就到最后了，然后不自动跳到下一首。
console里面有部分日志，不过看起来像是我手动切换下一首不能播放的情况
![2019-06-10_13-52.png](https://i.loli.net/2019/06/10/5cfdf018ab94458311.png)

**Comment by rocka** [comment]
我还是没能复现这个情况 ... 能不能给出当时正在听的歌单，然后是听到哪一首的时候不自动跳转的？

根据 log 看到这几首：

![image](https://user-images.githubusercontent.com/13914967/59277769-52dff180-8c93-11e9-9a6c-5c78f8f17bf9.png)

歌曲 id 分别是

```
419254936
411236140
37856499
505818432
```

我这里的表现是前两首没版权不能播放，自动跳过这两首以后后面的是没问题的 ...

**Comment by mengyaoss77** [comment]
@rocka   我之前是随机播放的，现在换回顺序播放再观察一段时间。

**Comment by mengyaoss77** [comment]
[![2019-06-12_20-06.png](https://i.loli.net/2019/06/12/5d00eb510be4566504.png)](https://i.loli.net/2019/06/12/5d00eb510be4566504.png)
来回测试 5遍左右的样子，测试方式均为直接拉进度条到快结束的位置，然后接着听到结尾。
44 -> 45  ok
45 -> 46  ok
46 -> 47  卡住在如图所示状态
手动跳到47 播放ok

但是，在我测试了后面几首歌之后，想回来看log的时候，发现又可以自动跳了。
无法稳定复现。
