### ISSUE TITLE
播放音乐的时候不能拖拽播放进度

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#41]
比如不能往前拖30sec。

**Comment by rocka** [comment]
拖拽是可以的吧，虽然拖进度条的时候可能会有点杂音，但这个功能是有的 …

至少也可以点击进度条的某个位置，直接跳转过去

**Comment by roachsinai** [comment]
Manjaro 0.8.9 点击进度条直接跳到最后，然后又直接跳到最开始从0开始播放。没办法拖拽╮（╯＿╰）╭

**Comment by rocka** [comment]
是我蠢了 ...
