### ISSUE TITLE
[Bug] Mac中热启动打开Uncaught Exception

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#42]
## 复现步骤
1. 不退出程序关机睡觉
2. 开机后程序图标驻留Docker
3. 点击在Docker中的图标进行**热启动**

## 报错内容

![image](https://user-images.githubusercontent.com/12933851/59737448-41e54080-9290-11e9-9a1e-3fe892624f77.png)

PS：
- 冷启动不会报错，只发生在热启动中
- 有错误后不影响程序的运行，只是每一次热启动打开都会有这个错误窗口，希望可以解决处理掉

**Comment by rocka** [comment]
虽然没有 mac ，但可以试着修一下 ...

**Comment by rocka** [comment]
来测一下最新的 CI Build 有没有修复呢？

**Comment by Gabirel** [comment]
那么问题来了，怎么测最新的CI build?

**Comment by rocka** [comment]
https://ncm-releases.herokuapp.com/

然后下载最上面的 darwin-x64

**Comment by rocka** [comment]
哎呀 ... 构建失败了

**Comment by Gabirel** [comment]
Fixed in https://github.com/Rocket1184/electron-netease-cloud-music/commit/0667871920f939c1915478c7dd9a40be9ece0f05

我为了测试还特意关机重启了两次，没有再遇到问题了。Ok了
