### ISSUE TITLE
开关托盘图标会显示多个图标

### ISSUE THREAD

**Issue by ShuiHuo** [Rocket1184/electron-netease-cloud-music#43]
![深度录屏_dde-desktop_20190712082303](https://user-images.githubusercontent.com/7471938/61093696-5cb96800-a47e-11e9-8926-d7cb13a722d5.gif)

**Comment by rocka** [comment]
可能是 electron 的 bug https://github.com/electron/electron/issues/17000

因为 KDE 也这样，不过多出来的托盘图标会默认被折叠起来，看不到 ...

**Comment by roachsinai** [comment]
xfce没有托盘图标怎么搞呢？谁能均我一个，😃

**Comment by haozibi** [comment]
看到动图，莫名喜感 haha

**Comment by supbose** [comment]
点一次托盘。销毁一次就行

**Comment by rocka** [comment]
should be fixed since Electron changed tray implementation: https://github.com/electron/electron/pull/36333
