### ISSUE TITLE
[Feature Request] 无热评时自动跳转到全部评论

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#45]
现在时「热评」和「全部评论」，但是没有「热评」的时候，默认的界面是待在「热评」的界面，需要自己手动点到「全部评论」。这个操作有点多余而且有点麻烦。

希望可以添加一个无热评时自动跳转到全部评论

**Comment by rocka** [comment]
closed via 85ab512
