### ISSUE TITLE
[Bug] 歌曲时常为60分钟时显示长度为00:00

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#46]
如图所示：
![image](https://user-images.githubusercontent.com/12933851/61222401-367d1c00-a74d-11e9-95b2-74f161bc268d.png)

**Comment by rocka** [comment]
我只试过时长接近一小时的歌曲，没想到还有超过一小时的 ...

**Comment by rocka** [comment]
closed via 198bf27
