### ISSUE TITLE
KDE下通过mpris api变更音量无效

### ISSUE THREAD

**Issue by AmazingRise** [Rocket1184/electron-netease-cloud-music#47]
OS: Arch Linux x64
DE: KDE Plasma 5

现象：
1. 无法通过KDE全局快捷键变更音量（设置-快捷键-全局快捷键-媒体控制器，媒体音量上升和媒体音量下降，我是在这里定义的快捷键）
2. 也无法通过KDE Connect变更音量（本人所用设备为Android）

翻了一下源码，貌似大佬针对DBus mpris api写了音量控制。
(目测在/src/main/mpris/mpris.js:310)
不知道为何会无效
迫于没Gnome环境，只有KDE实验过。
希望能够修复一下。

**Comment by rocka** [comment]
果然还是有人发现这个问题了 ...

现在 master 分支的代码是为 v0.9 准备的，但是还有很多东西没做完（具体看 [Projects - v0.9](https://github.com/Rocket1184/electron-netease-cloud-music/projects/2)）。MPRIS 的音量控制也是 v0.9 才会有的，因为之前用的 [sidorares/dbus-native](https://github.com/sidorares/dbus-native) 不支持通过 DBus 写入 Property，所以换成了 [dbusjs/node-dbus-next](https://github.com/dbusjs/node-dbus-next) ，重构了很多地方而且没怎么测试。

可以先到 https://ncm-releases.herokuapp.com/ 下载最新的 master 分支构建版本试一下，Arch 的话只用下载 asar 包，然后

```sh
electron /path/to/electron-netease-cloud-music_*.asar
```

就能运行了

**Comment by AmazingRise** [comment]
好的，我测试了，确实0.9版本的没有什么问题，音量可以正常调节。
不过当我开了新版之后，旧版的歌曲列表就加载不出来了。
看了一下todo列表，好像是更新了列表存储方式的缘故。
我去清除一波数据，应该就恢复正常了吧2333

**Comment by rocka** [comment]
是这样的 ...

应用设置 -> 启动开发者工具，然后把 IndexedDB 清掉就可以了。清除全部数据的话需要重新登录，还挺麻烦的 ...

<img src="https://user-images.githubusercontent.com/13914967/61871826-5c0be180-af14-11e9-9dc7-8d7b4b55ebbc.png" width="692">

**Comment by AmazingRise** [comment]
好的，十分感谢，辛苦作者啦！期待新版本的到来~

**Comment by rocka** [comment]
[`v0.9.0`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.0) 发布了 ...
