### ISSUE TITLE
清空播放列表后报错

### ISSUE THREAD

**Issue by VWWVVW** [Rocket1184/electron-netease-cloud-music#49]
![2019-07-27-224033_490x338_scrot](https://user-images.githubusercontent.com/30307767/61995799-b301ea00-b0bf-11e9-8c79-530c5dfb9753.png)

**Comment by rocka** [comment]
should be fixed by b4b0342, which ships in [`v0.8.17`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.8.17)
