### ISSUE TITLE
随机播放模式下，点击上一首和下一首的行为相同

### ISSUE THREAD

**Issue by AmazingRise** [Rocket1184/electron-netease-cloud-music#50]
刚才测试了一下，网易云原版客户端的随机播放，可以正常切换到上一首。
而此客户端的随机播放，无论点击上一首还是下一首都是pick随机的一首歌。

（主要是有的时候随机播放，不小心切换到下一首的时候就无法切回去了。）
希望能够对此作出改进~

**Comment by SamLukeYes** [comment]
而且随机播放的时候“下一首播放”的功能只会把歌曲加入播放列表，实际不一定下一首播放
