### ISSUE TITLE
[Feature Request] macOS下tray icon的位置无法被记住

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#51]
macOS下面tray icon的位置无法被记住。

1. tray icon在wifi的左右第一个，但是每次重启过后就会，tray icon就会跑到最左边，每次就需要拖过来很麻烦
![image](https://user-images.githubusercontent.com/12933851/62773682-5b0eae80-bad5-11e9-957a-e3e573987356.png)

2. 我本来以为是这个是排序软件的问题。但是我后来观察到，微信的tray icon就不会跑到最左边，而是会呆在上图的网络流量的左边。重启过后也不会乱跑，所以我推测，这个应该是一个特性。而非不可控的因素。

PS：由于我有一个按序排的tray软件来自动隐藏tray。大概是这样：（软件：Vanilla）
![image](https://user-images.githubusercontent.com/12933851/62773788-a923b200-bad5-11e9-92d6-7e3aaf68e649.png)

**Comment by rocka** [comment]
这我就真的不知道怎么回事了，没用过 macOS，而且 [Electron 的文档](https://electronjs.org/docs/api/tray)里也没提到过什么 `position` 或者 `priority` 之类的字段，创建托盘图标只是用一个 image 就可以 ...

**Comment by Gabirel** [comment]
其他的APP都可以记住这个位置的……为什么electron APP不可以，奇怪。

我不知道是不是跟 [ issue #52 ]有关系。建议先修复#52，再看看还会不会有问题。如果程序可以正常退出，或许可以保存住相关的东西。

**Comment by Gabirel** [comment]
#52 被修复以后，该问题还是继续存在，仍然无法记住当前tray icon在关闭前的状态😥

**Comment by Gabirel** [comment]
由于 #52 的修复，可以在重启过后保留当前的tray icon的位置，但是直接退出后再启动APP则不可以。

PS：wechat等程序两种均可以

**Comment by Gabirel** [comment]
在`v0.9.17`的版本中发现，如果不直接通过electron-NCM退出，直接系统级别关机。然后开机tray icon的位置可以恢复到开机前的状态。
但是，如果我直接从应用退出，再打开，tray icon的位置就又会默认跑到icon的最开头。

所以，我怀疑electron应该是可以有相应的功能可以保存类似的tray icon位置，但是应用程序因为没有采集相应的数据，所以没有把icon的位置记住？不知道这样的可能性有多大
