### ISSUE TITLE
[Feature Request] 不能播放的歌曲进行「暗色调」处理

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#55]
目前是播放的状态，自己的歌单中不能播放的歌曲只有在播放的时候才能知道是不是能够播放。

希望可以添加一个在歌单预览界面就可以预览到不能播放的歌曲。
只维护歌单中的是否播放状态，应该不会消耗太多资源吧？

**Comment by rocka** [comment]
获取歌单的歌曲列表的时候就有 `privilege` 这个字段的，应该是描述了歌曲能不能听，不过我还没研究过每个数字代表什么状态。

**Comment by rocka** [comment]
closed via 4f71617974da807ed7600a089867ac8a5f79c0dd
