### ISSUE TITLE
[Bug] macOS使用「网页登录」后不登录则无法退出

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#56]
版本：**v0.9.3**

选择网页登录后，会有一个弹窗来实现网页登录。

我知道在其他平台上 *应该* 是可以选择关闭的，但是我不确定。

在macOS上选择此种方式则没有相应的按钮。我不知道这是不是其他的平台也有，还是只有macOS上有。（如果只是macOS上的问题，那我会修改相应的issue的title）

截图所示：
因为采用堆叠显示的，所以只能看到最顶层的显示（e.g., 也就是下图），同时也看不到主界面。
![image](https://user-images.githubusercontent.com/12933851/64061961-a8cd9100-cc13-11e9-8b6c-44e18ee28811.png)

**Comment by rocka** [comment]
其他平台是有的，可是 macOS 居然没有，有点奇怪 ...

---

可能是因为 [这里](https://electronjs.org/docs/api/browser-window#platform-notices) 说的

> On macOS modal windows will be displayed as sheets attached to the parent window.

不过 sheets 是什么？反正不太懂

**Comment by Gabirel** [comment]
sheet参考见这个：https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/sheets/

效果的话就是，开一个页面，这个页面不是用的window dialog，pop-up dialog等形式的，是一个类似于一层sheet一样的东西从上往下铺展开的

**Comment by rocka** [comment]
没想到什么好办法，现在先检测到 macOS 就禁用 modal 选项了 ...

**Comment by Gabirel** [comment]
@rocka 这个解决了。

但是，在下面👇的图里，点击完成后没有响应。（即使是我取消登录操作，也应该完成可以关掉这个窗口，但是实际上没有办法关掉）
![image](https://user-images.githubusercontent.com/12933851/64475814-059fed00-d1ba-11e9-8483-60b7b20c5528.png)

**Comment by rocka** [comment]
cd5a4a5 这次应该好了吧 ...

**Comment by Gabirel** [comment]
https://github.com/Rocket1184/electron-netease-cloud-music/commit/cd5a4a5da6c3c84064e839125a73796e1d1be1d6#diff-8fffc8dfb88f306a93eff2c63d0ff9c6R195 这个地方是不是需要把这个临时登录窗口关掉呢？😂😂😂

不然只提醒一个然后用户关闭不是有点麻烦么？因为点完了之后是这样的：
![image](https://user-images.githubusercontent.com/12933851/64476486-d2f9f280-d1c1-11e9-9039-3fff9618f259.png)

**Comment by rocka** [comment]
这个地方指的是哪个窗口？如果到了上图这一步的话，弹出的网易云音乐窗口应该已经关闭了 ... 还是说哪里有出问题了 ...

**Comment by Gabirel** [comment]
过程就是这样的：

![2019-09-08 09-01-07 2019-09-08 09_03_42](https://user-images.githubusercontent.com/12933851/64481832-a4a70200-d217-11e9-9ee6-c59b29815d73.gif)

**Comment by rocka** [comment]
我认为这个算是合理的吧。登录不成功的原因，可能是用户主动关闭窗口，也可能是获取到的 cookie 是有问题的，这时候就应该需要再登录一次，所以我才会让它再弹回上一步 ...

我理解的你的想法应该是，如果主动关闭登录页面的窗口，那么主界面内这个登录步骤的对话框也应该一并关闭；

但根据我的想法，执行“打开登录页面”这个操作的使用者的目的应该就是成功登录，在登录页面这个窗口弹出之后应该也不会直接去关闭掉它 ...

**Comment by Gabirel** [comment]
这样啊。那代码层面就没啥问题了

那如果就是取消登录的话，就用户自己点击空白处取消么？这样的操作可能不是那么清晰吧～我是这样认为的。
