### ISSUE TITLE
歌名和歌不匹配

### ISSUE THREAD

**Issue by VWWVVW** [Rocket1184/electron-netease-cloud-music#57]
“Fallen Angel AKA Broken Arrow” 这首歌音频不对
网页上播放正常

**Comment by rocka** [comment]
我这边没有复现。关闭应用，找到 `~/.config/electron-netease-cloud-music/musicCache` ，然后删除以 `29239666` 开头的所有文件，再试试？

**Comment by VWWVVW** [comment]
并没有这个文件，我把musicCache里面的文件都清了，还是有问题
放的歌是“开心的战斗”。。。。。。

**Comment by rocka** [comment]
先把应用关掉，缓存删除之后，命令行运行

```console
env DEBUG=MusicServer electron-netease-cloud-music
```

打开应用，然后再听一下那首歌看看输出。

我这边是这样

```js
  MusicServer listening on { address: '::', family: 'IPv6', port: 44021 } +0ms
  MusicServer Request hit /music?id=532940100&quality=l +711ms
  MusicServer Hit cache for music id=532940100 +1ms
  MusicServer Request hit /music?id=29239666&quality=l +57s
  MusicServer res: { data: [ { id: 29239666, url: 'http://m7.music.126.net/20190914173628/83b34e1e1872a4e9a6dab6459f4cdcf7/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3', br: 128000, size: 3337865, md5: '53525e45fee3ace97dbe0fefc3e20d14', code: 200, expi: 1200, type: 'mp3', gain: 0, fee: 0, uf: null, payed: 0, flag: 0, canExtend: false, freeTrialInfo: null, level: 'standard', encodeType: 'mp3' } ], code: 200 } +165ms
  MusicServer Got URL for music id=29239666 +1ms
  MusicServer Finish downloading music id=29239666, md5=53525e45fee3ace97dbe0fefc3e20d14 +448ms
```

**Comment by VWWVVW** [comment]
第一次运行没有输出，第二次运行输出：
`  MusicServer listening on { address: '::', family: 'IPv6', port: 40367 } +0ms
  MusicServer Request hit /music?id=29239666&quality=l +2s
  MusicServer res: { data: [ { id: 29239666, url: 'http://m8.music.126.net/20190914174553/19aed62e7e7c3b5fe8afb66ffcd0a44f/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3', br: 128000, size: 3337865, md5: '53525e45fee3ace97dbe0fefc3e20d14', code: 200, expi: 1200, type: 'mp3', gain: 0, fee: 0, uf: null, payed: 0, flag: 0, canExtend: false, freeTrialInfo: null, level: 'standard', encodeType: 'mp3' } ], code: 200 } +498ms
  MusicServer Got URL for music id=29239666 +2ms
  MusicServer Download music id=29239666 hash mismatch, delete it ... +1s
  MusicServer Request hit /music?id=29239666&quality=l +6s
  MusicServer res: { data: [ { id: 29239666, url: 'http://m8.music.126.net/20190914174600/6f5d6b2885147c8d71f791c0ce991aad/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3', br: 128000, size: 3337865, md5: '53525e45fee3ace97dbe0fefc3e20d14', code: 200, expi: 1200, type: 'mp3', gain: 0, fee: 0, uf: null, payed: 0, flag: 0, canExtend: false, freeTrialInfo: null, level: 'standard', encodeType: 'mp3' } ], code: 200 } +245ms
  MusicServer Got URL for music id=29239666 +1ms
  MusicServer Download music id=29239666 hash mismatch, delete it ... +934ms
`

**Comment by VWWVVW** [comment]
第一次运行没有输出，第二次运行输出：
```
  MusicServer listening on { address: '::', family: 'IPv6', port: 40367 } +0ms
  MusicServer Request hit /music?id=29239666&quality=l +2s
  MusicServer res: { data: [ { id: 29239666, url: 'http://m8.music.126.net/20190914174553/19aed62e7e7c3b5fe8afb66ffcd0a44f/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3', br: 128000, size: 3337865, md5: '53525e45fee3ace97dbe0fefc3e20d14', code: 200, expi: 1200, type: 'mp3', gain: 0, fee: 0, uf: null, payed: 0, flag: 0, canExtend: false, freeTrialInfo: null, level: 'standard', encodeType: 'mp3' } ], code: 200 } +498ms
  MusicServer Got URL for music id=29239666 +2ms
  MusicServer Download music id=29239666 hash mismatch, delete it ... +1s
  MusicServer Request hit /music?id=29239666&quality=l +6s
  MusicServer res: { data: [ { id: 29239666, url: 'http://m8.music.126.net/20190914174600/6f5d6b2885147c8d71f791c0ce991aad/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3', br: 128000, size: 3337865, md5: '53525e45fee3ace97dbe0fefc3e20d14', code: 200, expi: 1200, type: 'mp3', gain: 0, fee: 0, uf: null, payed: 0, flag: 0, canExtend: false, freeTrialInfo: null, level: 'standard', encodeType: 'mp3' } ], code: 200 } +245ms
  MusicServer Got URL for music id=29239666 +1ms
  MusicServer Download music id=29239666 hash mismatch, delete it ... +934ms

```

**Comment by rocka** [comment]
md5 mismatch ，会不会是 CDN 问题或者被劫持了 ... 直接在浏览器里打开 http://m8.music.126.net/20190914174600/6f5d6b2885147c8d71f791c0ce991aad/ymusic/0468/2e15/ecda/53525e45fee3ace97dbe0fefc3e20d14.mp3 这个 URL 听听得到的是什么歌呢

**Comment by VWWVVW** [comment]
是开心的战斗

**Comment by rocka** [comment]
把协议改成 https 试试呢？

**Comment by rocka** [comment]
我听到的是 “Fallen Angel AKA Broken Arrow” ，怀疑是网易 CDN 的问题 ...

**Comment by VWWVVW** [comment]
https听到的是Fallen Angel AKA Broken Arrow

**Comment by rocka** [comment]
哦那也有可能是网络运营商 http 缓存的问题。那以后的版本尝试把所有的歌曲 URL 都用 https 吧。

**Comment by VWWVVW** [comment]
wow谢谢
