### ISSUE TITLE
[Bug] 永远都是「歌词加载中」，刷新歌词无效

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#59]
![image](https://user-images.githubusercontent.com/12933851/66263739-60188180-e82a-11e9-8fa2-a4cb321cebff.png)

即使出现了刷新歌词，也还是刷不出来

**Comment by rocka** [comment]
这个我没能复现 ... 打开 console 看看有没有报错呢？

**Comment by Gabirel** [comment]
点击「刷新歌词」后的console：（换一首歌的时候也会出现这个问题）
![image](https://user-images.githubusercontent.com/12933851/66270570-da2b2380-e887-11e9-8cea-5be6e976d4b2.png)

**Comment by rocka** [comment]
切换到 `Application` 的 tab ，看看 IndexedDB 里面是不是少了东西

![image](https://user-images.githubusercontent.com/13914967/66270846-853cdc80-e88a-11e9-8fa0-8590d9be20fd.png)

在 `electron-ncm` DB 中应该存在 lyric / playlist / radio / tracks 四个 table ，这里像是少了 lyric table

顺便其它依赖 IndexedDB 的功能，比如私人 FM 历史记录，和打开时恢复上一次退出的播放列表，这两个正常吗？

**Comment by Gabirel** [comment]
1. 的确少了一个lyric的table
![image](https://user-images.githubusercontent.com/12933851/66278591-1046c280-e8dd-11e9-82ce-299de116c1b1.png)

2. 私人FM历史记录正常
3. 打开时恢复上一次推出的播放列表正常

**Comment by rocka** [comment]
这个情况应该是用了 master 分支上还没开发完成的版本，把 IndexedDB 给搞乱了 ... 只能删库重来了

1. 在控制台执行这些，把播放列表和私人 FM 历史记录存到 localStorage 里面去。如果不在意这些东西可以跳过这一步：

	```js
	window.onbeforeunload = null;
	['playlist', 'radio'].forEach(k => localStorage.setItem(k, JSON.stringify(document.body.lastElementChild.__vue__.$store.state[k])))
	```

2. 然后删库：

	选中 `electron-ncm` 这个 db ，点击 Delete Database ，之后重开程序
	
	![image](https://user-images.githubusercontent.com/13914967/66279818-39b81c00-e8e6-11e9-9710-616aa0a2fe73.png)

**Comment by Gabirel** [comment]
1. 为什么未开发完全的版本是在master分支？😂

2. 问题解决

**Comment by rocka** [comment]
现在只一个 master 分支，只有一个人的业余项目，懒得搞 git flow 那一套了 …

以前有一个 dev 分支的，又要搞 CI 还要 merge 分支太麻烦了
