### ISSUE TITLE
歌手名字太长。。。导致把进度条顶出去了

### ISSUE THREAD

**Issue by a-wing** [Rocket1184/electron-netease-cloud-music#62]
![image](https://user-images.githubusercontent.com/18189138/69121821-2d73d100-0ad8-11ea-8a28-3cf4fccee44c.png)

**Comment by rocka** [comment]
这里还有个问题，歌手太多的话，歌词上面的歌手列表会换很多行，把歌词挤到下面去。而且换行之后， `专辑` 前面还会多空出来一格的空间，不太好看 ...
