### ISSUE TITLE
README里的图片资源失效

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#63]
如题所示。

![image](https://user-images.githubusercontent.com/12933851/69967610-bd436180-1553-11ea-8865-2fcd9be19130.png)

**Comment by rocka** [comment]
我这没问题， README 里面的图片都是在发 Release 的时候直接从 Releast Note 的编辑框里面上传的，除非 GitHub 自己爆炸了 ... 要是真的爆炸了我们也没办法 😅

![image](https://user-images.githubusercontent.com/13914967/70018759-1a75fc00-15c2-11ea-9440-c3c7c53d0536.png)

![image](https://user-images.githubusercontent.com/13914967/70018814-42655f80-15c2-11ea-9a15-f97b644c129e.png)
