### ISSUE TITLE
[Question] 本地播放列表不会影响网易云已听歌曲统计

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#66]
对于本地的播放列表中的播放歌曲，这些播放貌似是离线本地化的，不会计算在网易云本书的歌曲统计中。

在这个地方会看得到已播放的歌曲：
![image](https://user-images.githubusercontent.com/12933851/71665517-3d015d80-2d98-11ea-8b0c-2815b330e43f.png)

可能这个算是feature quest，我不确定。另外，这个功能点的话会影响到私人FM的数据。但是由于每次的歌曲都是离线本地的，对私人FM好像几乎没有任何的影响，这点就有一点困扰了

**Comment by rocka** [comment]
实际上并没有对本地已缓存的歌曲和未缓存的歌曲做区别对待，每次歌曲播放完成之后都会去请求一下“增加听歌记录”这个 API

https://github.com/Rocket1184/electron-netease-cloud-music/blob/fe67ee58f46aadf7f7eca41c8339113f6c287513/src/renderer/components/PlayerBar/PlayerBar.vue#L405-L407

因为这个是从网页版上抓来的，每个参数的含义都不是很确定，而且不一定每次都有用 ...

**Comment by Gabirel** [comment]
所以，可以说是实际上会反馈给网易云的？至少代码层面是有的？

可是我测试了三天的，「还需听歌xxxx首」那里真的没有变化呀～私人FM的倒是有变化的

**Comment by rocka** [comment]
我记得刚加入这段代码的时候的确是有用的，大概一个月之前仍然有用，但现在如果没用的话也没办法 … 或者可以测试一下用网页版听几首歌会不会有变化

当然如果能抓到手机或者 PC 客户端上传听歌信息的包那是最好了 …

**Comment by rocka** [comment]
观察了几天，我发现听歌统计其实是有效的，只不过不会立即表现在数字上，大概第二天就能看到数字增加了。 v0.9.9 版增加了用户页面以及听歌排行的功能，应该可以看得到。

**Comment by Gabirel** [comment]
测试过有用（至少现在有用）。之前的确是没有记录进去的，不知道为什么。如果后续还有问题，我再反馈
