### ISSUE TITLE
[Feature Request] 设置网络代理

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#68]
能不能增加应用内设置(socks5)代理服务器？我试了常用的环境变量似乎没有效果，使用proxychains就直接出core dump (这个是electron的问题)

**Comment by rocka** [comment]
v0.9.9 把 `node-fetch` 换成了 `electron-fetch` ，应该会遵守系统代理设置了 ... 但是没有手动设置代理的界面，可以测试一下环境变量是否有效

**Comment by ylxdzsw** [comment]
有效！！ 感谢～
