### ISSUE TITLE
[Question] 托盘菜单中的字体问题

### ISSUE THREAD

**Issue by sxyugao** [Rocket1184/electron-netease-cloud-music#69]
托盘菜单中的图标乱码了，请问需要什么字体才能解决？

**Comment by rocka** [comment]
随便一个 Emoji 字体就好， Noto Color Emoji, Emoji One, JoyPixels, 或者 Symbola 这类符号字体也可以。

**Comment by roachsinai** [comment]
OS: Manjaro

![image](https://user-images.githubusercontent.com/9500049/79086356-50946b00-7d6e-11ea-83bd-60dbef2cbe15.png)

Joy 并不是完全支持，上图是Joy字体。

**Comment by roachsinai** [comment]
由于我用的是KDE，必须调整`常规`字体才能让electron-netease-cloud-music使用对用的字体。

![image](https://user-images.githubusercontent.com/9500049/79086433-981af700-7d6e-11ea-936d-252b274cabd8.png)

这就导致，比如我用noto-emoji的时候全局菜单栏上的日期都是emoji字体，而使用Symbola，这个直接字体全称俄文了。

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/79086802-f2688780-7d6f-11ea-8ef6-309570cdfec4.png)

**Comment by rocka** [comment]
@roachsinai 不，不是这么配置的，常规字体当然不能设置为 Emoji ，你需要配置一下 fontconfig 的 fallback 顺序，也就是 ~/.config/fontconfig/fonts.conf 这个文件，或者抄一下现成的配置，比如我的这个： https://github.com/rocka/dotFiles/blob/b72567c0d3b07279bdfd07810a6082fbf8bc1a27/.config/fontconfig/fonts.conf

我用的 Emoji 字体是 Blobmoji ，用别的字体需要自行调整，以及 Roboto 英文字体和 Noto Sans CJK 中文字体也需要单独安装。

**Comment by roachsinai** [comment]
下面是我的配置，之后后面的`serif`和`mono`是根据你的添加修改的，剩下的是默认就有的。

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="pattern">
  <test name="family" qual="any">
   <string>monospace</string>
  </test>
  <edit name="family" mode="assign" binding="same">
   <string>Hack</string>
  </edit>
 </match>
 <dir>~/.fonts</dir>
 <match target="font">
  <edit name="hinting" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hintstyle" mode="assign">
   <const>hintfull</const>
  </edit>
 </match>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>rgb</const>
  </edit>
 </match>
 <!-- serif -->
 <alias>
  <family>serif</family>
  <prefer>
   <family>Noto Serif</family>
   <family>Noto Serif CJK SC</family>
   <family>Noto Color Emoji</family>
  </prefer>
 </alias>
 <!-- monospace -->
 <match>
  <test name="family">
   <string>monospace</string>
  </test>
  <edit mode="prepend" name="family" binding="strong">
   <string>Iosevka</string>
   <string>Noto Sans Mono</string>
   <string>Noto Sans Mono CJK SC</string>
   <string>Noto Color Emoji</string>
  </edit>
 </match>
</fontconfig>
```

**Comment by roachsinai** [comment]
但是，修改注销之后还是不显示emoji。

**Comment by roachsinai** [comment]
😄，成了，跟着这篇文章：[Linux下终极字体配置方案 | Micheal's Blog](https://ohmyarch.github.io/2017/01/15/Linux%E4%B8%8B%E7%BB%88%E6%9E%81%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE%E6%96%B9%E6%A1%88/)

感谢！

**Comment by rocka** [comment]
@roachsinai 

> 下面是我的配置，之后后面的`serif`和`mono`是根据你的添加修改的，剩下的是默认就有的。

你这个配置里面没有配 sans-serif ，而只有 sans-serif 对这个问题是有用的 ...

**Comment by roachsinai** [comment]
嗯，主要是之前我也不懂为什么这么设置。看了上面那个链接之后懂了一些。想求助一下，我的Konsole在右键编辑当前方案的时候，前面有个图标不显示。看您的配置好像用的也是KDE，能否发一下呢？

![image](https://user-images.githubusercontent.com/9500049/79112363-f9fc5080-7db0-11ea-83dd-20165c43677c.png)

不过这个有些offline了。

**Comment by roachsinai** [comment]
难道这不是个乱码？😄
