### ISSUE TITLE
无法播放歌曲

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [Rocket1184/electron-netease-cloud-music#7]
archlinux 从 archlinux-cn repo 安装， 可以登陆， 但是播放歌曲时会显示歌曲无法播放， 换下一首把

**Comment by rocka** [comment]
在网易云音乐网页版可以播放吗？有没有开启系统代理或者设置 `HTTP_PROXY` 之类的环境变量？

**Comment by rocka** [comment]
原因应该是这个 https://github.com/Binaryify/NeteaseCloudMusicApi/pull/291

已经登录过的用户不受影响，但是新登录或者未登录的用户就会被判定为 `Cheating`

**Comment by rocka** [comment]
https://github.com/Rocket1184/electron-netease-cloud-music/commit/c3807a18f4690000c16ea6f2357ba880f1766665 应该已经修好了

可以来 [这里](https://ncm-releases.herokuapp.com/) 下载最新的 release 试用
