### ISSUE TITLE
Crash report  v0.9.9

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#70]
![Screenshot from 2020-02-23 02-41-21](https://user-images.githubusercontent.com/7145046/75097472-11eff900-55e6-11ea-9070-7e4d1b55b92f.png)

**Comment by ylxdzsw** [comment]
好吧，好像是我网络的问题。不过这又带来了一个问题，有一些歌没下载完网断了，然后这个corrupted的文件却被cache住了，每次播放到上次跳出的时候就会停止直接下一曲。有没有办法识别这种情况，或者保证一首歌顺利播放完成了再写缓存？

另外加载失败的图片好像也被cache住了😂
![Screenshot from 2020-02-23 02-50-35](https://user-images.githubusercontent.com/7145046/75097620-c63e4f00-55e7-11ea-9801-9fecdaccaa12.png)

**Comment by rocka** [comment]
来试试最新的 CI 构建吧，尝试修复了 `CONTENT_LENGTH_MISMATCH` 的问题，但是得先在设置里面清除一下歌曲缓存，把下坏了的文件都清掉 ... 这个缓存处理的部分可能也得重构一下，这个需要一些时间。

至于图片加载失败的问题，如果再遇到的话，能不能打开开发者工具看一下，是图片 URL 算错了导致 404 ，还是网络的问题。

**Comment by ylxdzsw** [comment]
图片看了一下是404，链接是 https://p3.music.126.net/hmZoNQaqzZALvVp0rE7faA==/0.jpg?param=64y64 而其它正常的音乐图片那一段base64样的东西后面是一个差不多10多位的数字，不是0，而且param也是40y40。

歌曲缓存已经清除了，目前再没有遇到这个问题，不过本来也就不能稳定复现就是。。

**Comment by rocka** [comment]
音乐云盘里面的歌曲是没有专辑封面的，URL 的数字那部分就变成 0 了 ... v0.9.10 里面对云盘里面的歌曲特殊处理了一下，加了个默认封面图片。但从旧版升级上来的话，需要把歌曲从播放列表里面移除一下，再添加进去才能生效。

**Comment by ylxdzsw** [comment]
赞！
