### ISSUE TITLE
通过网页登录功能坏掉啦

### ISSUE THREAD

**Issue by AmazingRise** [Rocket1184/electron-netease-cloud-music#71]
复现步骤: 断开网络,打开electron-ncm,点击用户头像登录,选择网页登录,出现music.163.com的窗口
输入帐号密码,登录成功,并且可以在这个网页里面签到
关掉网页,app显示登录不成功

=。=所以我是哪里操作出错了吗。。
环境： Archlinux 64bit
版本： 0.9.12-1

**Comment by AmazingRise** [comment]
顺便说一句，主页的Todos该更新了，新的音乐云盘功能属实给力

**Comment by rocka** [comment]
这个确实是出问题了，正常的话登录完成之后网页应该会自动关掉的 ...

**Comment by AmazingRise** [comment]
> 这个确实是出问题了，正常的话登录完成之后网页应该会自动关掉的 ...
> 
> **Edit:** 因为网页登录的 URL 匹配错了，邮箱登录是可以的，但是手机号登录会没反应

等一下,我就是用邮箱登录的...

**Comment by rocka** [comment]
可能我测试的时候已经改掉一部分代码了 😅

在 v0.9.14 修好了
