### ISSUE TITLE
Could not login

### ISSUE THREAD

**Issue by PeppaCat** [Rocket1184/electron-netease-cloud-music#73]
- Problem: Failed to login.
When trying to login through user and passwd, it says *request to https://music.163.com/weapi/login failed, reason: net::ERR_CONNECTION_REFUSED*
When trying to login through website authentication, it web could not load (blank).
- Environment: manjaro KDE 5.4.22-1, installed through AUR. electron version:8.0.1

**Comment by rocka** [comment]
Wired, it works fine on my Arch Linux and other Manjaro machines.

1. Can you access and login https://music.163.com/ through chromium or your web browser?

2. Do you see any recommend playlists when you open the App? Or only some blank cards?

3. Do you use have sort of network proxy, if you do, how do you configure them? Via KDE systemsettings, environment variable, iptables or other?

**Comment by PeppaCat** [comment]
Thank you for reminding. The problem is caused by network configuring. When I use China Mobile, it fails. But as soon as I convert to wireless network in my home, it successes immediately. Hope this would help others encountering the same problems
