### ISSUE TITLE
[Feature Request] macOS端打开微软雅黑字体后界面异常丑

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#74]
## 期许行为
在Enable微软雅黑字体后，界面不会发生变化，如图所示：
![image](https://user-images.githubusercontent.com/12933851/76179748-e892b800-61f6-11ea-85ba-247d98c0389c.png)

![image](https://user-images.githubusercontent.com/12933851/76179754-ee889900-61f6-11ea-97b2-bb8f01bc43ca.png)

![image](https://user-images.githubusercontent.com/12933851/76179792-09f3a400-61f7-11ea-8221-240c2e953205.png)

## 实际行为
打开雅黑字体后，界面发生特别严重的变化（丑）。总体来说，字体更加「硬朗」了，也稍微粗了一点，没有自带的字体好看了，其他的程序没有这样的问题。
![image](https://user-images.githubusercontent.com/12933851/76180408-cd28ac80-61f8-11ea-92d1-520900509712.png)

![image](https://user-images.githubusercontent.com/12933851/76180310-90f54c00-61f8-11ea-8429-7b2ab33ed1e9.png)

![image](https://user-images.githubusercontent.com/12933851/76180301-8935a780-61f8-11ea-967c-dd1e34fbd54b.png)

当前版本：v0.9.15-0-gee17978

**Comment by rocka** [comment]
macOS 默认的字体名字是什么， `PingFang SC` 吗？

打开开发者工具，选中 `<body>` ，然后把 font-family 里面的 `Microsoft Yahei` 改成 `PingFang SC` 试试呢

![image](https://user-images.githubusercontent.com/13914967/76183949-1aab1680-6205-11ea-9d89-c512c7f66498.png)

**Comment by Gabirel** [comment]
改成`PingFang SC`后与原来的字体一样。在enable和disable后，字体没有变化。所以应该是`PingFang SC`

**Comment by Gabirel** [comment]
已经在`v0.9.16-1-g86a895f`中修复这个问题
