### ISSUE TITLE
[Bug] 微信登录需要操作两次才能登录成功

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#75]
版本：v0.9.15-0-gee17978

需要点登录两次，第二次才能自动关闭窗口，以及登录成功。

这个问题在很久以前就有了，甚至在0.8也存在这个问题。流程可参考GIF（GIF图片略大，耐心加载）

![trimmed 2020-03-09 19_52_37](https://user-images.githubusercontent.com/12933851/76211241-bf971500-6240-11ea-9dca-12d7da7a2163.gif)

相关的issue：https://github.com/Rocket1184/electron-netease-cloud-music/issues/71

**Comment by rocka** [comment]
这似乎是个 Electron 的问题，不知道为什么，读取登录响应中的 cookie 的时候，页面崩溃了。就是你所见的，微信扫描二维码登录后，后面的页面整个变白了。

**Comment by Gabirel** [comment]
所以就等待新版本eletron？以此来解决这个问题？

**Comment by rocka** [comment]
去掉了一个看上去与这个问题没什么关系的选项，但应该是修好了，试试 0.9.16 吧

**Comment by Gabirel** [comment]
已经正常工作了👍
