### ISSUE TITLE
Manjaro i3wm 无法显示托盘图标

### ISSUE THREAD

**Issue by APPTOOSTILL** [Rocket1184/electron-netease-cloud-music#76]
我用的是manjaro i3wm 。最近一次更新之后，软件图标在系统托盘上就显示不出来了，是不是跟electron更新有关，想请教一下解决方案。

**Comment by rocka** [comment]
没用过 i3wm ，不知道你用的是什么应用来现实托盘。现在 Electron 的托盘图标是由 StatusNotifierItem 实现的，可能需要你自己来寻找一下相关的解决方案了。

**Comment by realparisio** [comment]
electron/electron#21445

**Comment by dotenorio** [comment]
See my solution:

https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150

**Comment by rocka** [comment]
see also https://github.com/polybar/polybar/issues/2010

**Comment by Block81838** [comment]
im usin i3wm too, my tray icon is work
![20200724-221443](https://user-images.githubusercontent.com/22847876/88449359-191c6c80-cdfb-11ea-8a42-bb6a964ab7c5.png)

**Comment by thaoeu** [comment]
我用的trayer，可以加载出。
![Q08'21-0108](https://user-images.githubusercontent.com/34019378/108706630-d6b23e00-7549-11eb-9bda-24bd69a0f465.png)
