### ISSUE TITLE
[Bug] 无法加载搜索结果

### ISSUE THREAD

**Issue by SnowzTail** [Rocket1184/electron-netease-cloud-music#79]
- 版本号: 0.9.17 (AUR)

如图, 搜索栏返回联想内容, 但无法加载搜索结果页面. 是海外 ip 的原因吗?

![2020-04-01_21-30](https://user-images.githubusercontent.com/30973137/78183616-1d91d380-7460-11ea-9e77-6e099cc670fd.png)

**Comment by rocka** [comment]
登录帐号了吗？有时候不登录的话是搜索不出结果的，但好像也不至于这样报错 ...

https://github.com/Rocket1184/electron-netease-cloud-music/blob/d315a97806c3d4d35d0fb0e887186e0dc06ebf4f/src/renderer/store/actions.js#L261-L266

错误在 262 行，`result.songs` 是 `undefined`

控制台输入

```js
localStorage.debug = 'API'
```

开启调试日志，然后按 <kbd>Ctrl</kbd> + <kbd>R</kbd> 重载一下窗口，再搜索一下试试看。

正常的话结果应该是这样的

![image](https://user-images.githubusercontent.com/13914967/78203854-a6ddf000-74ca-11ea-8057-43d8adbd5cab.png)

**Comment by SnowzTail** [comment]
登录帐号了呢

这样的 log 可以吗?

![2020-04-02_13-16](https://user-images.githubusercontent.com/30973137/78248292-4360bc00-74e4-11ea-8368-ecb6e13081f8.png)

**Comment by rocka** [comment]
足够发现问题了，网易云音乐的一些 API 针对海外 IP 似乎有特殊的加密，但目前还没研究过 ...

**Comment by SnowzTail** [comment]
十分感谢~

**Comment by rocka** [comment]
除了搜索，别的地方还会出现数据不能加载的问题吗？

**Comment by SnowzTail** [comment]
> 除了搜索，别的地方还会出现数据不能加载的问题吗？

其他都没问题的

**Comment by rocka** [comment]
懒得研究那个加密算法了，反正也是旧版的 API ，现在换成 Android 客户端用的新 API 了，应该没问题了。

来试试最新的 CI 构建版本吧： https://ncm-releases.herokuapp.com/

Arch 的话只要下载 asar 文件，然后

```sh
electron /path/to/file.asar
```

就能运行了

**Comment by SnowzTail** [comment]
解决啦~赞赞赞ヾ(๑╹ヮ╹๑)ﾉ"

十分感谢ww

**Comment by rocka** [comment]
问题解决了的话，别忘了在控制台里面执行一下

```js
localStorage.debug = null
```

关掉 debug log ，不然会内存泄漏的 …

**Comment by SnowzTail** [comment]
> 问题解决了的话，别忘了在控制台里面执行一下
> 
> ```js
> localStorage.debug = null
> ```
> 
> 关掉 debug log ，不然会内存泄漏的 …

明白~
