### ISSUE TITLE
下面图片中的乱码是字体原因么？

### ISSUE THREAD

**Issue by roachsinai** [Rocket1184/electron-netease-cloud-music#80]
![image](https://user-images.githubusercontent.com/9500049/79063390-0e1e5000-7cd4-11ea-9416-14230c7432f0.png)

**Comment by rocka** [comment]
是字体问题，建议安装一个符号字体（如 Symbola ）或者 Emoji 字体。 #69

https://github.com/Rocket1184/electron-netease-cloud-music/blob/df47455ae0c31af731174bd073056c3bbe73067b/src/main/tray.js#L178-L179
