### ISSUE TITLE
点击关注的时候不会显示是否关注成功

### ISSUE THREAD

**Issue by SamLukeYes** [Rocket1184/electron-netease-cloud-music#81]
当你在一个已经把你拉黑的用户的主页点关注的时候，会显示已关注并且ta的粉丝+1，但重新进入这个页面的时候仍然显示未关注。

**Comment by rocka** [comment]
我是真的没想到网易云居然还能拉黑的，写这个页面的时候就没考虑关注居然还能失败。行吧，一会加上。

**Comment by rocka** [comment]
should be fixed in 65642d3f01e8121437923ef7f2c5854171b6e721 but not released yet

**Comment by rocka** [comment]
released [`v0.9.19`](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.19)
