### ISSUE TITLE
播放列表的逻辑

### ISSUE THREAD

**Issue by cjc7373** [Rocket1184/electron-netease-cloud-music#82]
## 当前行为
播放某个歌单的歌时，将该首歌添加至播放列表中。

## 预期的行为
当播放某个歌单的歌时，这个歌单会将当前的播放列表覆盖。
Android 和 UWP 端都是这个逻辑。
（或者做个选项切换也行？

**Comment by rocka** [comment]
我个人是不太喜“替换播放列表”的这个行为的 ... 而且很多功能是我觉得“有用”才加入的，而不是完全去照抄其它客户端的操作逻辑。但是现在既然有这个需求了，做个选项好像也可以 ...
