### ISSUE TITLE
Tray icon is missing

### ISSUE THREAD

**Issue by Block81838** [Rocket1184/electron-netease-cloud-music#87]
Archlinux + i3 desktop
-----------------------------
 ### Tray icon is not ***shown*** when I try to open tray icon

**Comment by rocka** [comment]
Which software do you use to implement the tray? If they do not support StatusNotifierItem protocol, the icon wont't be shown.

Also try to install or uninstall `libappindicator-gtk3` to force electron switch between sni and xembed tray implemention.
