### ISSUE TITLE
[Bug] 正在播放的歌曲和其评论不对应

### ISSUE THREAD

**Issue by Gabirel** [Rocket1184/electron-netease-cloud-music#88]
## 问题
如下图所示，当前的歌曲是：Thunder & Rain 歌手是：Echoes of Nature
![image](https://user-images.githubusercontent.com/12933851/84850919-882fd400-b08b-11ea-9b2f-1d769c22d79e.png)

这个对应的这个评论是之前听过的某一首歌（可以从截图中看出「杰克斯派若」这个关键词，可以知道是加勒比海盗）的评论，**不知道什么原因导致歌曲播放那边刷新了**（更多见下面），但是评论没有刷新。

## 真正的加勒比海盗的评论
找不到这首歌了……

## 真正的Thunder & Rain的评论
已在手机端和网页端验证过
![image](https://user-images.githubusercontent.com/12933851/84851486-fcb74280-b08c-11ea-8bca-748559d6872e.png)

## 其他歌曲错乱展示
可以知道这首歌不是录制雨声的，是我以前听过的某一首关于雨声的。这里也错误。**因此可见这个问题不是偶然性问题**
![image](https://user-images.githubusercontent.com/12933851/84851227-48b5b780-b08c-11ea-86d7-994b100ab25b.png)

## 可能的复现方法
- 步骤1
在私人FM中随便点一首，这里我选择「사이렌 - 宣美」。（不管私人FM是不是被勾选，都会触发）
![image](https://user-images.githubusercontent.com/12933851/84851877-fe353a80-b08d-11ea-8750-f0665685f67f.png)

下图是进一步的展示：图中的评论是宣美的这首歌评论。
![image](https://user-images.githubusercontent.com/12933851/84851628-5e77ac80-b08d-11ea-9658-ea3beaffa677.png)

- 步骤2
在私人FM的列表中，选择「삐삐 - IU」
![image](https://user-images.githubusercontent.com/12933851/84851628-5e77ac80-b08d-11ea-9658-ea3beaffa677.png)

- 步骤3
点击播放，可以发现它的评论不刷新，仍然是之前宣美的歌曲的评论
![image](https://user-images.githubusercontent.com/12933851/84851673-836c1f80-b08d-11ea-9373-67928f01a1dd.png)

**PS：尚不清楚是否还有其他复现方法，目前我只发现了这个**

**Comment by cjc7373** [comment]
歌曲改变后评论不会刷新, 这应该是预期的行为.

**Comment by rocka** [comment]
哦哦，一开始没看懂是什么意思，还以为是点评论按钮进入评论页面的时候会加载错 ...

这个是预期的行为，在评论页面已经打开的情况下，切换歌曲不会导致评论内容重新加载，一开始想的是在看评论的时候如果突然被切掉了会很不爽吧。但这里想表达的是，在“手动”切歌之后，评论也跟着切换，对吧？

**Comment by Gabirel** [comment]
> 但这里想表达的是，在“手动”切歌之后，评论也跟着切换，对吧？

对

--------

> 一开始想的是在看评论的时候如果突然被切掉了会很不爽吧。

那如果是从这个角度考虑的话，我觉得可以接受。那就关闭这个吧
