### ISSUE TITLE
[Bug] 部分 SnackBar 会夺取窗口全部焦点

### ISSUE THREAD

**Issue by Mivik** [Rocket1184/electron-netease-cloud-music#89]
如题，某些情况弹出的 SnackBar（如签到时弹出的“签到成功”）会夺取窗口焦点，导致点击窗口其他部分没有响应，SnackBar 消失后方能继续操作

**Comment by rocka** [comment]
具体是在哪个界面上呢？我倒是没遇到过 ...

**Comment by rocka** [comment]
好吧，因为一直在用自动签到，没机会发现这个

**Comment by rocka** [comment]
should be fixed by https://github.com/rocka/muse-ui/commit/c2b2764681d4911551fca5e8216c95c4e37ca8eb and https://github.com/Rocket1184/electron-netease-cloud-music/commit/5ef5454c63f850ac73c1115910237ff8be992300#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L46
