### ISSUE TITLE
Play in random order?

### ISSUE THREAD

**Issue by ylxdzsw** [Rocket1184/electron-netease-cloud-music#9]
I have just installed this app from AUR and it works very well. However, a must-have feature for me is missing: play in random order. It is not mentioned in [TODOs](https://github.com/Rocket1184/electron-netease-cloud-music#todos). Is there any plan about it? I can also help in implementing.

**Comment by rocka** [comment]
Roger. Will be implemented soon.

**Comment by rocka** [comment]
closed via 266e8e8 , please upgrade to v0.6.0 and have a try

**Comment by ylxdzsw** [comment]
Great, thanks!
