### ISSUE TITLE
无法登录了......(原谅我英语不好QAQ)

### ISSUE THREAD

**Issue by ClarkAbe** [Rocket1184/electron-netease-cloud-music#91]
手机号登录提示:request to https://music.163.com/weapi/login/cellphone failed, reason: net::ERR_PROXY_CONNECTION_FAILED
网页登录加载不出来,用浏览器就可以登录.....

**Comment by rocka** [comment]
…… 检查一下系统代理设置，以及 HTTP_PROXY 环境变量之类的

**Comment by ClarkAbe** [comment]
好的

发自我的iPhone

在 2020年6月30日，23:16，rocka <notifications@github.com> 写道：

﻿

…… 检查一下系统代理设置，以及 HTTP_PROXY 环境变量之类的

**Comment by ClarkAbe** [comment]
我制杖，脑子宕机了.......忘了关全局socks
