### ISSUE TITLE
Dwm 无法使用音频按键

### ISSUE THREAD

**Issue by thaoeu** [Rocket1184/electron-netease-cloud-music#92]
刚刚试了下播放暂停切换曲目全都不能用，不知道是不是个例

**Comment by rocka** [comment]
准确地说，应用本体是不支持键盘上的媒体按键的，只是实现了 MPRIS ，而由媒体按键到 MPRIS 的映射一般是由 DE 来完成的。可能 dwm 并没有提供这个功能？

**Comment by thaoeu** [comment]
非常感谢，按找你的思路我用dbus命令实现了媒体控制
`
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.ElectronNCM /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
`
`
	{ 0,							XF86XK_AudioNext, spawn, {.v = playnext} },
`
并且设置了dwm热键，问题已经完美解决。

**Comment by thaoeu** [comment]
未来有添加本地播放的计划吗，现在播放本地音乐还要装别的软件。

**Comment by rocka** [comment]
> 未来有添加本地播放的计划吗

有计划添加管理已经缓存的歌曲的功能，但是单纯的导入并播放本地歌曲暂时不在计划中。

**Comment by thaoeu** [comment]
> > 未来有添加本地播放的计划吗
> 
> 有计划添加管理已经缓存的歌曲的功能，但是单纯的导入并播放本地歌曲暂时不在计划中。

哦哦，好的谢谢
