### ISSUE TITLE
[New Feature] 启动到托盘

### ISSUE THREAD

**Issue by Core00077** [Rocket1184/electron-netease-cloud-music#93]
希望可以通过命令行或者设置开关等方式，在启动的时候不显示主界面（即启动到托盘）。好处是软件开机自启动的时候就直接藏在系统托盘里了，想播放的时候直接快捷键播放即可。（懒人+音乐爱好者）

目前通过系统设置了开机自动启动，然而每次都得手动叉掉才能最小化到托盘，希望大佬有空写写，感谢

**Comment by Core00077** [comment]
另外对于开机自启动的需求还有个别的问题：对于wifi用户，随系统启动的网易云音乐是未联网状态的，所以开机自启大多数情况的后果是显示用户未登录，而联网后再启动网易云基本都可以使用之前的session自动登录。

逻辑上应该可以通过判断联网状态来自动登录吧？不知道好不好做，希望可以有。如果有需要这个需求我可以再开个issue，先谢谢大佬了。

**Comment by rocka** [comment]
[v0.9.25](https://github.com/Rocket1184/electron-netease-cloud-music/releases/tag/v0.9.25) 新增了设置选项 “启动时最小化到托盘” (0b81e2ebbfbf5073b36aac2f85d849b5c50b65e0)， 以及登录前判断联网状态 (d8ad49292de4e565fb9a4f8ffc68eed2535c3003)
