### ISSUE TITLE
[New Feature] 启动时记住上次的音量

### ISSUE THREAD

**Issue by Core00077** [Rocket1184/electron-netease-cloud-music#94]
希望软件启动的时候，软件内的音量大小保持上次启动时设置的值。

**Comment by rocka** [comment]
不能记住音量吗？我试了一下是可以的 ...

另外试一下打开私人 FM 后再退出，再启动的时候是不是能记住私人 FM 开启的状态。

**Comment by Core00077** [comment]
感谢回复，最近较忙所以拖了有点久。重新测试了下，在重新打开和重启两种情况下都不能记住音量。

——直到后面打开的私人FM再退出——私人FM的开关记住了，音量也记住了。可能是个私人FM启动才开启了本地记录吧。issue先关了
