### ISSUE TITLE
[Feature Request] 桌面浮动歌词栏

### ISSUE THREAD

**Issue by vycezhong** [Rocket1184/electron-netease-cloud-music#97]
很有用的feature，请问有计划做吗？

**Comment by rocka** [comment]
暂时不在计划中。Linux 用户可以考虑使用 [osdlyrics](https://github.com/osdlyrics/osdlyrics) ([AUR](https://aur.archlinux.org/packages/osdlyrics-python3-git/)) ，选择网易的歌词源，可以完美匹配

**Comment by vycezhong** [comment]
i see. thx,

**Comment by poly000** [comment]
现在仍在todo吗？
