### ISSUE TITLE
当列表中歌曲均无法播放时暂停播放

### ISSUE THREAD

**Issue by VWWVVW** [Rocket1184/electron-netease-cloud-music#99]
目前当列表中歌曲均无法播放时会重复提醒该歌曲无法播放，播放下一首，不停循环歌单，并且按下暂停键也没用

**Comment by rocka** [comment]
这个应该属于 bug 吧 ...

**Comment by rocka** [comment]
fixed by 0d1540c35dea41b33a60274d67fcebff91b99bb5
